#!/bin/sh
# make sure chgrp handles --recursive w/symlinks

if test "$VERBOSE" = yes; then
  set -x
  chgrp --version
fi

. $srcdir/../group-names

pwd=`pwd`
tmp=slink.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit
fi

set _ $groups; shift
g1=$1
g2=$2

fail=0

# chgrp -R should not traverse a symlink to a directory.
mkdir d e
touch e/f
ln -s ../e d/s
chgrp -R $g1 e/f || fail=1
# Neither of the following should change the group of e/f
chgrp -R $g2 d
set _ `ls -l e/f`; g=$5; test "$g" = $g1 || fail=1
chgrp --deref -R $g2 d
set _ `ls -l e/f`; g=$5; test "$g" = $g1 || fail=1

# Even when the symlink-to-directory is a command line argument, it should
# not be traversed.  So this shouldn't change the group of e/f either.
chgrp --deref -R $g2 d/s || fail=1
set _ `ls -l e/f`; g=$5; test "$g" = $g1 || fail=1

(exit $fail); exit
