#!/bin/sh
# Make sure dd does the right thing when the input file descriptor
# is not rewound.

if test "$VERBOSE" = yes; then
  set -x
  dd --version
fi

pwd=`pwd`
tmp=dd-rw.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0

echo abcde > in
(dd skip=1 count=1 bs=1; dd skip=1 bs=1) < in > out 2> /dev/null || fail=1
case `cat out` in
  bde) ;;
  *) fail=1 ;;
esac

(exit $fail); exit $fail
