#!/bin/sh
# make sure du's --exclude option works

if test "$VERBOSE" = yes; then
  set -x
  du --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir -p a/b/c a/x/y a/u/v

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

du --exclude=x a | sed 's/^[0-9][0-9]*	//' | sort > out || fail=1
printf '===\n'
printf 'b\n' > excl
du --exclude-from=excl a | sed 's/^[0-9][0-9]*	//' | sort > out || fail=1
cat <<\EOF > exp
a/b/c
a/b
a/u/v
a/u
a
===
a/x/y
a/x
a/u/v
a/u
a
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
