#!/bin/sh
# Make sure `du d/1 d/2' works.
# That command failed with du from fileutils-4.0q.

if test "$VERBOSE" = yes; then
  set -x
  du --version
fi

tmp=du2-$$
trap 'status=$?; rm -rf $tmp && exit $status' 0
trap 'exit $?' 1 2 13 15

mkdir -p $tmp/1 $tmp/2

test -d $tmp || fail=1
du $tmp/1 $tmp/2 > /dev/null || fail=1

exit $fail
