#!/bin/sh
# Make sure `du d/1 d/2' works.
# That command failed with du from fileutils-4.0q.

if test "$VERBOSE" = yes; then
  set -x
  du --version
fi

pwd=`pwd`
tmp=du2-$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

mkdir -p $tmp/1 $tmp/2

test -d $tmp || fail=1
du $tmp/1 $tmp/2 > /dev/null || fail=1

# Make sure `du . $tmp' and `du .. $tmp' work.
# These would fail prior to fileutils-4.0y.
du . $tmp > /dev/null || fail=1
du .. $tmp > /dev/null || fail=1

(exit $fail); exit
