#!/bin/sh
# Just like p-1, but with an absolute path.

if test "$VERBOSE" = yes; then
  set -x
  mkdir --version
fi

pwd=`pwd`
tmp=`echo "$0"|sed 's,.*/,,'`.tmp
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

mkdir --parents $tmp || fail=1

test -d $tmp || fail=1

exit $fail
