#!/bin/sh
# Verify that mkdir's `-m MODE' option works properly
# with various umask settings.

if test "$VERBOSE" = yes; then
  set -x
  mkdir --version
fi

pwd=`pwd`
tmp=perm.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

fail=0

# umask   -m option   resulting perm
tests='
    000  :            :drwxrwxrwx:
    000  :   -m 016   :d-----xrw-:
    077  :            :drwx------:
    050  :            :drwx-w-rwx:
    050  :   -m 312   :d-wx--x-w-:
    160  :            :drw---xrwx:
    -    :   -        :last:
    '
for p in empty -p; do
  test _$p = _empty && p=

  old_IFS=$IFS
  IFS=':
'
  set - $tests
  IFS=$old_IFS

  while :; do
    umask=$1 mode=$2 expected_perms=$3
    test $expected_perms = last && break
    shift; shift; shift
    umask $umask
    mkdir $p $mode d || fail=1

    actual_perms=`ls -ld d | sed 's/ .*//'`
    test "$expected_perms" = "$actual_perms" \
      || { fail=1; echo expected $expected_perms, got $actual_perms; }
    rmdir d || fail=1
  done
done

(exit $fail); exit
