language: cpp
matrix:
  include:
  - name: Ubuntu with gcc on amd64 and -O0
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_gcc_o0
    - CFLAGS="-O0"
  - name: Ubuntu with gcc on amd64 and -O1
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_gcc_o1
    - CFLAGS="-O1"
  - name: Ubuntu with gcc on amd64 and -O2
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_gcc_o2
    - CFLAGS="-O2"
  - name: Ubuntu with gcc on amd64 and -O3
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_gcc_o3
    - CFLAGS="-O3"
  - name: Ubuntu with clang on amd64 and -O0
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_clang_o0
    - CFLAGS="-O0"
  - name: Ubuntu with clang on amd64 and -O1
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_clang_o1
    - CFLAGS="-O1"
  - name: Ubuntu with clang on amd64 and -O2
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_clang_o2
    - CFLAGS="-O2"
  - name: Ubuntu with clang on amd64 and -O3
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env:
    - TPCP_OPTIONS=amd64_linux_clang_o3
    - CFLAGS="-O3"
#  - name: Ubuntu with gcc on arm64 and -O0
#    os: linux
#    dist: bionic
#    compiler: gcc
#    arch: arm64
#    env:
#    - TPCP_OPTIONS=arm64_linux_gcc_o0
#    - CFLAGS="-O0"
#  - name: Ubuntu with gcc on arm64 and -O1
#    os: linux
#    dist: bionic
#    compiler: gcc
#    arch: arm64
#    env:
#    - TPCP_OPTIONS=arm64_linux_gcc_o1
#    - CFLAGS="-O1"
#  - name: Ubuntu with gcc on arm64 and -O2
#    os: linux
#    dist: bionic
#    compiler: gcc
#    arch: arm64
#    env:
#    - TPCP_OPTIONS=arm64_linux_gcc_o2
#    - CFLAGS="-O2"
#  - name: Ubuntu with gcc on arm64 and -O3
#    os: linux
#    dist: bionic
#    compiler: gcc
#    arch: arm64
#    env:
#    - TPCP_OPTIONS=arm64_linux_gcc_o3
#    - CFLAGS="-O3"
#  - name: Windows with gcc on amd64 and -O0
#    os: windows
#    compiler: gcc
#    arch: amd64
#    env:
#    - TPCP_OPTIONS=amd64_windows_gcc_o0
#    - CFLAGS="-O0"
#  - name: Windows with gcc on amd64 and -O1
#    os: windows
#    compiler: gcc
#    arch: amd64
#    env:
#    - TPCP_OPTIONS=amd64_windows_gcc_o1
#    - CFLAGS="-O1"
#  - name: Windows with gcc on amd64 and -O2
#    os: windows
#    compiler: gcc
#    arch: amd64
#    env:
#    - TPCP_OPTIONS=amd64_windows_gcc_o2
#    - CFLAGS="-O2"
#  - name: Windows with gcc on amd64 and -O3
#    os: windows
#    compiler: gcc
#    arch: amd64
#    env:
#    - TPCP_OPTIONS=amd64_windows_gcc_o3
#    - CFLAGS="-O3"

before_install:
- |-
  export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  export CFLAGS=${CFLAGS}" "${ENV_CXXFLAGS}
  # we need to turn off warning errors because of some declaration type mismatches
  # in the header files that get installed in windows, and optimization changes 
  # appear to cause some other warnings to appear.
  export CFLAGS=${CFLAGS}" -Wno-error"
  case ${TRAVIS_OS_NAME} in
    linux)
      sudo apt-get update && sudo apt-get install -y texinfo gettext gperf autoconf automake bison perl autopoint
      export cmd_prefix=""
      ;;
    windows)
      [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
      choco uninstall -y mingw
      choco upgrade --no-progress -y msys2
      export cmd_prefix='cmd //C RefreshEnv.cmd '
      export cmd_prefix+='& set MSYS=winsymlinks:nativestrict '
      export cmd_prefix+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
      export cmd_prefix+=" -msys2 -c "\"\$@"\" --" 
      $cmd_prefix pacman -Syu
      $cmd_prefix pacman --sync --noconfirm --needed base-devel make gcc texinfo
      ;;
  esac 

script:
- ./bootstrap
#- $cmd_prefix ../tpcp-build-helper.sh
- $cmd_prefix ./configure
- $cmd_prefix make
- $cmd_prefix make check

before_cache:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      # https://unix.stackexchange.com/a/137322/107554
      $cmd_prefix pacman --sync --clean --noconfirm
      ;;
  esac

# cache magic, baby (otherwise, windows config takes for. ev. er.)
cache:
  directories:
  - $HOME/AppData/Local/Temp/chocolatey
  - /C/tools/msys64

branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"

deploy:
  provider: releases
  api_key:
    secure: L/rnY17GVcU/jStcS9PuD157tG0Q8Wx9qh46ZLhGw/q/X9nZS+bpC7GQ6xCHflx189oDhZmksLRQuxJoxWo4e5QP2QRnlCAhoZdDTCpIZNDRfN0iEnLU0BWFCVZjoMdRhVuADM6hTWjhCgUBuHnZ0/gX8UKVkrnxUPQNs4hGyjMbnEAIdGbdzsJsPeS0sqNIvtG+b6qppeswkNDQqoUD+OBg/+iP93AJySBzMLtxR8hCUdHM/PfKQEHwRWf0LkRYDS1gUkg4lr6NSBvVPZtqLv8SVlQRfxuCLOQ30Na14aWVLzDS/0bI1ETlkUXKvWLYWATEkaXsteFk4rhJbKp04PO6nm9PDDJ6QUGzT8zUcPpuYmBVTAMTEKCYrYxnLcLQbbo7KIDymgrjVOuSIPrfcMzmFqy9tJ4LXbt9Pjr2TmSXz0/nFDtnYMuOzHEi0nTHb3Yf048eLm+fSdMSOJrvsrQ2SGryzb4//Y6Sm874x/OoXp+72qv1yS6RafkS+s3xNVFOZn/441QmvBQkEXMR3knizQ84KalZ70AhKEa2xkxZcUKqjMreuyZz8sDhQh3Ia/lNGNrd9UY7jWN4aJbltfra/G8sNBPFD8W9gdJq5WjvQ5d4VPCYaUH5GNvmWMIjvpmXAnQh+DNy1XCuuHNTvvOlKw99wBoqo50c4qVyls4=
  file_glob: true
  file: final-exe/*
  skip_cleanup: true
  on:
    repo: tpcp-project/coreutils

