# Customize Makefile.maint.                           -*- makefile -*-
# Copyright (C) 2003, 2004 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

# Use alpha.gnu.org for alpha and beta releases.
# Use ftp.gnu.org for major releases.
gnu_ftp_host-alpha = alpha.gnu.org
gnu_ftp_host-beta = alpha.gnu.org
gnu_ftp_host-major = ftp.gnu.org
gnu_rel_host = $(gnu_ftp_host-$(RELEASE_TYPE))

url_dir_list = \
  ftp://$(gnu_rel_host)/gnu/coreutils \
  http://fetish.sf.net

# Files to update automatically.
wget_files = \
  $(srcdir)/config/config.guess \
  $(srcdir)/config/config.sub \
  $(srcdir)/config/texinfo.tex
# Of the above, texinfo.tex is out of date,
# and the other two are not available.
wget_files =

cvs_files = \
  $(srcdir)/config/elisp-comp \
  $(srcdir)/config/depcomp \
  $(srcdir)/config/mdate-sh \
  $(srcdir)/config/missing \
  $(srcdir)/config/install-sh \
  $(srcdir)/config/mkinstalldirs

#  $(srcdir)/src/ansi2knr.c

local_updates = wget-update cvs-update

# Tests not to run.
local-checks-to-skip =
