#!/bin/sh
# cp -RL d1 d2' must handle the case in which d1 and d2 both contain
# a symlink pointing to some third directory.

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir a b c d || framework_failure=1
ln -s ../c a || framework_failure=1
ln -s ../c b || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

cp -RL a b d || fail=1
test -d a/c || fail=1
test -d b/c || fail=1

(exit $fail); exit $fail
