#!/bin/sh
# Test basic --backup functionality for both cp and mv.

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

LANGUAGE=C; export LANGUAGE
LANG=C; export LANG

umask 022

pwd=`pwd`
dir=cpmvbak-$$
actual=$dir/actual
expected=$dir/expected
trap "cd $pwd; rm -rf $dir" 0 1 2 3 15

mkdir $dir
unset VERSION_CONTROL SIMPLE_BACKUP_SUFFIX

if test "${VERSION_CONTROL+set}" = set; then
  echo '$0: the VERSION_CONTROL envvar is set --' \
    ' unset it and rerun this test' >&2
  exit 1
fi

if test "${SIMPLE_BACKUP_SUFFIX+set}" = set; then
  echo '$0: the SIMPLE_BACKUP_SUFFIX envvar is set --' \
    ' unset it and rerun this test' >&2
    >&2
  exit 1
fi

exec 1> $actual

fail=0
for prog in cp mv; do
  for initial_files in 'x' 'x y' 'x y y~' 'x y y.~1~' 'x y y~ y.~1~'; do
    for opt in none off  numbered t  existing nil  simple never; do
      ( cd $dir; touch $initial_files )
	$prog --backup=$opt $dir/x $dir/y || fail=1
      ( cd $dir; echo $initial_files $opt: `ls [xy]*`; rm -f x y y~ y.~?~ )
    done
  done
done

cat <<\EOF > $expected-tmp
x none: x y
x off: x y
x numbered: x y
x t: x y
x existing: x y
x nil: x y
x simple: x y
x never: x y
x y none: x y
x y off: x y
x y numbered: x y y.~1~
x y t: x y y.~1~
x y existing: x y y~
x y nil: x y y~
x y simple: x y y~
x y never: x y y~
x y y~ none: x y y~
x y y~ off: x y y~
x y y~ numbered: x y y.~1~ y~
x y y~ t: x y y.~1~ y~
x y y~ existing: x y y~
x y y~ nil: x y y~
x y y~ simple: x y y~
x y y~ never: x y y~
x y y.~1~ none: x y y.~1~
x y y.~1~ off: x y y.~1~
x y y.~1~ numbered: x y y.~1~ y.~2~
x y y.~1~ t: x y y.~1~ y.~2~
x y y.~1~ existing: x y y.~1~ y.~2~
x y y.~1~ nil: x y y.~1~ y.~2~
x y y.~1~ simple: x y y.~1~ y~
x y y.~1~ never: x y y.~1~ y~
x y y~ y.~1~ none: x y y.~1~ y~
x y y~ y.~1~ off: x y y.~1~ y~
x y y~ y.~1~ numbered: x y y.~1~ y.~2~ y~
x y y~ y.~1~ t: x y y.~1~ y.~2~ y~
x y y~ y.~1~ existing: x y y.~1~ y.~2~ y~
x y y~ y.~1~ nil: x y y.~1~ y.~2~ y~
x y y~ y.~1~ simple: x y y.~1~ y~
x y y~ y.~1~ never: x y y.~1~ y~
EOF

sed 's/: x/:/' $expected-tmp |cat $expected-tmp - > $expected

# Uncomment this if you see a failure and want to try to diagnose it.
#diff -u $expected $actual 1>&2

cmp $expected $actual || fail=1

exit $fail
