#!/bin/sh
# verify that cp's --remove-destination option works with -R

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

pwd=`pwd`
tmp=cprmdest.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir d e || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0

# Do it once with no destination...
cp -R --remove-destination d e || fail=1

# ...and again, with an existing destination.
cp -R --remove-destination d e || fail=1

(exit $fail); exit
