#!/bin/sh

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

mkdir D D/D || framework_failure=1
touch D/a || framework_failure=1
chmod 0 D/a || framework_failure=1
chmod 500 D || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0

# This is expected to exit non-zero, because it can't read D/a.
cp -pR D DD > /dev/null 2>&1 && fail=1

# Permissions on DD must be `dr-x------'

set X `ls -ld DD`
shift
test "$1" = dr-x------ || fail=1

chmod 0 D
ln -s D/D symlink
touch F
cat > exp <<\EOF
cp: accessing `symlink': Permission denied
EOF

cp F symlink 2> out && fail=1
cmp out exp || { (diff -c out exp) 2> /dev/null; fail=1; }

cp --target-directory=symlink F 2> out && fail=1
cmp out exp || { (diff -c out exp) 2> /dev/null; fail=1; }

chmod 700 D

(exit $fail); exit $fail
