#!/bin/sh
# Make sure cp --link -f works when the target exists.
# This failed for 4.0z (due to a bug introduced in that test release).

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp;tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

touch src || framework_failure=1
touch dest || framework_failure=1
touch dest2 || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0

cp -f --link src dest || fail=1
cp -f --symbolic-link src dest2 || fail=1

(exit $fail); exit $fail
