#!/bin/sh
# ensure that `cp -d' preserves hard-links between command line arguments

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default

pwd=`pwd`
tmp=lp.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
touch a || framework_failure=1
ln a b || framework_failure=1
mkdir c || framework_failure=1
cp -d a b c || framework_failure=1
test -f c/a || framework_failure=1
test -f c/b || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit
fi

fail=0

a_inode=`ls -i c/a|sed 's,c/.*,,'`
b_inode=`ls -i c/b|sed 's,c/.*,,'`

test "$a_inode" = "$b_inode" || fail=1

(exit $fail); exit
