#!/bin/sh
# FIXME: This test requires ln -s.
# cp from 3.16 fails this test

rm -rf a b
mkdir a b
msg=bar
echo $msg > a/foo
cd b
ln -s ../a/foo .
cd ..

# It should fail with a message something like this:
#   ./cp: `a/foo' and `b/foo' are the same file
./cp -d a/foo b 2>/dev/null

# Fail this test if the exit status is not 1
test $? = 1 || exit 1

test "`cat a/foo`" = bar || exit 1

exit 0
