#!/bin/sh
# FIXME: This test requires ln -s.
# cp from 3.16 fails this test

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

msg=bar
echo $msg > a
ln -s a b

fail=0

# It should fail with a message something like this:
#   cp: `a' and `b' are the same file
cp -d a b 2>/dev/null

# Fail this test if the exit status is not 1
test $? = 1 || fail=1

test "`cat a`" = $msg || fail=1

(exit $fail); exit
