#!/bin/sh
# FIXME: This test requires ln -s.
# cp from 3.16 fails this test

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

rm -rf a b
mkdir b
msg=bar
echo $msg > a
cd b
ln -s ../a .
cd ..

fail=0

# It should fail with a message something like this:
#   cp: `a' and `b/foo' are the same file
cp -d a b 2>/dev/null

# Fail this test if the exit status is not 1
test $? = 1 || fail=1

test "`cat a`" = $msg || fail=1

rm -rf a b

(exit $fail); exit
