#!/bin/sh
# Exercise the fix for http://debbugs.gnu.org/8419

# Copyright (C) 2011 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
print_ver_ cp

same_inode()
{
  local u v
  u=$(stat --format %i "$1") &&
    v=$(stat --format %i "$2") && test "$u" = "$v"
}

mkdir -p s t/s || framework_failure_
touch s/f t/s/f || framework_failure_
ln s/f s/link || framework_failure_

# This must create a hard link, t/s/link, to the existing file, t/s/f.
# With cp from coreutils-8.12 and prior, it would mistakenly copy
# the file rather than creating the link.
cp -au s t || fail=1

same_inode t/s/f t/s/link || fail=1

Exit $fail
