#!/bin/sh
# cp -r should not create symlinks.  Fixed in fileutils-4.1.5.
# Restored old behavior (whereby cp -r preserves symlinks) in 4.1.6,
# though now such usage evokes a warning:
# cp: `slink': WARNING: using -r to copy symbolic links is not portable

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

. $srcdir/../envvar-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp;tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
echo abc > foo || framework_failure=1
ln -s foo slink || framework_failure=1
ln -s no-such-file no-file || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# This would fail in 4.1.5, not in 4.1.6.
cp -r no-file junk 2>/dev/null || fail=1

cp -r slink bar 2>/dev/null || fail=1
set x `ls -l bar`; shift; mode=$1
case $mode in
  l*) ;;
  *) fail=1;;
esac

(exit $fail); exit $fail
