#!/bin/sh
# cp -r should not create symlinks.  Fixed in fileutils-4.1.5.

if test "$VERBOSE" = yes; then
  set -x
  cp --version
fi

. $srcdir/../envvar-check

pwd=`pwd`
tmp=r-vs-slink.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
echo abc > foo || framework_failure=1
ln -s foo slink || framework_failure=1
ln -s no-such-file no-file || framework_failure=1

if test $framework_failure = 1; then
  echo '$0: failure in testing framework' 1>&2
  (exit 1); exit
fi

fail=0

# This must fail.
cp -r no-file junk 2>/dev/null && fail=1

cp -r slink bar || fail=1
set x `ls -l bar`; shift; mode=$1
case $mode in
  l*) fail=1;;
esac

(exit $fail); exit
