#!/bin/sh
# FIXME

# Copyright (C) 2008 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  FIXME --version
fi

# FIXME: . $srcdir/../envvar-check
# FIXME: . $srcdir/../lang-default
. $srcdir/../test-lib.sh
# FIXME: skip_if_root_
# FIXME: require_root_

# If used, these must *follow* test-lib.sh.
# FIXME: cleanup_() { rm -rf "$other_partition_tmpdir"; }
# FIXME: . "$abs_top_srcdir/tests/other-fs-tmpdir"

fail=0
FIXME > out || fail=1
cat <<\EOF > exp || fail=1
FIXME
EOF

compare out exp || fail=1

(exit $fail); exit $fail
