#!/bin/sh
# in coreutils-8.12, this would have required ~1GB of memory

# Copyright (C) 2011 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
print_ver_ rm

very_expensive_

# Put 4M files in a directory.
mkdir d && cd d || framework_failure_
seq 4000000|xargs touch || framework_failure_

cd ..

# Restricted to 50MB, rm from coreutils-8.12 would fail with a
# diagnostic like "rm: fts_read failed: Cannot allocate memory".
ulimit -v 50000
rm -rf d || fail=1

Exit $fail
