#!/bin/sh
# rm should not prompt before removing a dangling symlink.
# But for fileutils-4.1.9, it would.

if test "$VERBOSE" = yes; then
  set -x
  rm --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
ln -s no-file dangle

if test $framework_failure = 1; then
  echo '$0: failure in testing framework' 1>&2
  (exit 1); exit
fi

fail=0

# Skip this test if there is no /dev/stdin file.
ls /dev/stdin >/dev/null 2>&1 \
  || { (exit 77); exit; }

rm dangle < /dev/stdin &
pid=$!

# The buggy rm (fileutils-4.1.9) would hang here, waiting for input.
sleep 1

# The file must no longer exist.
ls -l dangle > /dev/null 2>&1 && fail=1

kill $pid > /dev/null 2>&1

(exit $fail); exit
