#!/bin/sh

# This is a bit of a torture test for mkdir -p, too.

: ${RM=rm}
: ${MKDIR=mkdir}

test=deep-1

# Don't require use of TMPDIR.
: ${RM_TMPDIR=.}

if test "$VERBOSE" = yes; then
  set -x
  $RM --version
fi

umask 022

fail=0

tmp=$RM_TMPDIR/t-rm.$$

k20=/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k/k
k200=$k20$k20$k20$k20$k20$k20$k20$k20$k20$k20
k_deep=$k200$k200

# Create a directory in $tmp with lots of `k' components.
deep=$tmp$k_deep
$MKDIR -p $deep || fail=1

find $tmp > k

# Make sure the deep dir was created.
test -d $deep || fail=1

$RM -r $tmp || fail=1

# Make sure it was deleted.
test -d $deep && fail=1

exit $fail
