#!/bin/sh
# rm (without -r) must give a diagnostic for any directory.
# It must not prompt, even if that directory is unwritable.

if test "$VERBOSE" = yes; then
  set -x
  rm --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir --mode=0500 unwritable-dir || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# For rm from coreutils-5.0.1, this would prompt.
rm --presume-input-tty unwritable-dir < /dev/null > out-t 2>&1 && fail=1
cat <<\EOF > exp || fail=1
rm: cannot remove `unwritable-dir': Is a directory
EOF

# When run by a non-privileged user we get this:
# rm: cannot remove directory `unwritable-dir': Is a directory
# When run by root we get this:
# rm: cannot remove `unwritable-dir': Is a directory
# Normalize the message.
sed 's/remove directory/remove/' out-t > out
rm -f out-t

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
