#!/bin/sh

: ${RM=rm}
test=i-1

if test "$VERBOSE" = yes; then
  set -x
  $RM --version
fi

# Don't require use of TMPDIR.
: ${RM_TMPDIR=.}

tmp=$RM_TMPDIR/t-rm.$$

test_failure=0
mkdir $tmp || test_failure=1
echo > $tmp/a || test_failure=1
test -f $tmp/a || test_failure=1

if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

echo y > $tmp/$test.Iy
echo n > $tmp/$test.In

fail=0
$RM -i $tmp/a < $tmp/$test.In > /dev/null 2>&1 || fail=1
# The file should not have been removed.
test -f $tmp/a || fail=1

$RM -i $tmp/a < $tmp/$test.Iy > /dev/null 2>&1 || fail=1
# The file should have been removed this time.
test -f $tmp/a && fail=1

rm -rf $tmp

exit $fail
