#!/bin/sh
# With rm from coreutils-5.2.1 and earlier, `rm -r' would mistakenly
# give up too early under some conditions.

if test "$VERBOSE" = yes; then
  set -x
  rm --version
fi

PRIV_CHECK_ARG=require-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir d
touch d/f
chown -R $NON_ROOT_USERNAME d
chmod u=rwx .

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# This must fail, since `.' is not writable by $NON_ROOT_USERNAME.
setuidgid $NON_ROOT_USERNAME env PATH=$PATH rm -rf d 2>/dev/null && fail=1

# d must remain.
test -d d || fail=1

# f must have been removed.
test -f d/f && fail=1

(exit $fail); exit $fail
