#!/bin/sh
# Demonstrate rm's new --one-file-system option.

# Copyright (C) 2006 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if test "$VERBOSE" = yes; then
  set -x
  rm --version
fi

PRIV_CHECK_ARG=require-root . $srcdir/../priv-check
. $srcdir/../lang-default
. $srcdir/../other-fs-tmpdir

if test -z "$other_partition_tmpdir"; then
  (exit 77); exit 77
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

t0="$t0 $other_partition_tmpdir"

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

t=$other_partition_tmpdir
mkdir -p a/b $t/y
mount --bind $t a/b || framework_failure=1

cat <<\EOF > exp || framework_failure=1
rm: skipping `a/b', since it's on a different device
EOF

if test $framework_failure = 1; then
  echo "$0: setup failed; skipping this test" 1>&2
  (exit 77); exit 77
fi

fail=0

rm --one-file-system -rf a 2> out && fail=1
test -d $t/y || fail=1
umount $t

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
