#!/bin/sh

if test "$VERBOSE" = yes; then
  rm --version
  set -x
fi

. $srcdir/../lang-default

pwd=`pwd`
tmp=r2-$$
trap 'status=$?; cd $pwd; rm -rf $tmp || exit $?; exit $status' 0
trap 'exit $?' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp

mkdir t t/a t/a/b || framework_failure=1
> t/a/f || framework_failure=1
> t/a/b/g || framework_failure=1

# FIXME: if this fails, it's a framework failure
cat <<EOF | sort > t/E || framework_failure=1
removing all entries of directory \`t/a'
removing all entries of directory \`t/a/b'
removing \`t/a/b/g'
removing the directory itself: \`t/a/b'
removing \`t/a/f'
removing the directory itself: \`t/a'
EOF

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

# Note that both the expected output (above) and the actual output lines
# are sorted, because directory entries may be processed in arbitrary order.
fail=0
rm --verbose -r t/a | sort > t/O || fail=1

if test -d t/a; then
  fail=1
fi

# Compare expected and actual output.
cmp t/E t/O || fail=1

exit $fail
