#!/bin/sh

if test "$VERBOSE" = yes; then
  rm --version
  set -x
fi

. $srcdir/../lang-default

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp;tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 || exit $?; exit $status' 0
trap 'exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp

mkdir t t/a t/a/b || framework_failure=1
> t/a/f || framework_failure=1
> t/a/b/g || framework_failure=1

# FIXME: if this fails, it's a framework failure
cat <<\EOF | sort > t/E || framework_failure=1
removed directory: `t/a'
removed directory: `t/a/b'
removed `t/a/b/g'
removed `t/a/f'
EOF

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

# Note that both the expected output (above) and the actual output lines
# are sorted, because directory entries may be processed in arbitrary order.
fail=0
rm --verbose -r t/a | sort > t/O || fail=1

if test -d t/a; then
  fail=1
fi

# Compare expected and actual output.
cmp t/E t/O || fail=1
test $fail = 1 && diff t/E t/O 2> /dev/null

(exit $fail); exit
