#!/bin/sh
# Create and remove a directory with more than 254 files.
# An early version of my rewritten rm failed to remove all of
# the files on SunOS4 when there were 254 or more in a directory.

if test "$VERBOSE" = yes; then
  rm --version
  set -x
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp;tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_fail=0
mkdir -p $tmp || framework_fail=1
cd $tmp || framework_fail=1

# Create 300 files (12 * 25).
for i in 0 1 2 3 4 5 6 7 8 9 a b; do
  files=
  for j in a b c d e f g h i j k l m n o p q r s t u v w x y; do
    files="$files $i$j"
  done
  touch $files || framework_fail=1
done

test -f 0a || framework_fail=1
test -f by || framework_fail=1
cd .. || framework_fail=1

if test $framework_fail = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

fail=0
rm -rf $tmp || fail=1
test -d $tmp && fail=1

(exit $fail); exit
