#!/bin/sh
# a basic test of rm -ri

if test "$VERBOSE" = yes; then
  set -x
  rm --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default
PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir -p d/e || framework_failure=1
cat <<EOF > in || framework_failure=1
y
y
y
EOF

cat <<\EOF > exp || framework_failure=1
rm: descend into directory `d'
rm: remove directory `d/e'
rm: remove directory `d'
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

rm -ir d < in > out 2>&1 || fail=1
tr '?' '\012' < out |sed 's/^ //' > o2
mv o2 out

# Make sure it's been removed.
test -d d && fail=1

cmp out exp || fail=1
test $fail = 1 && diff -u out exp 2> /dev/null

(exit $fail); exit
