#!/bin/sh
# Ensure that cat outputs processed data immediately.

# Copyright (C) 2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  cat --version
fi

. $srcdir/test-lib.sh

# Use a fifo rather than a pipe in the tests below
# so that the producer (cat) will wait until the
# consumer (dd) opens the fifo therefore increasing
# the chance that dd will read the data from each
# write separately.
mkfifo fifo || framework_failure

fail=0

echo 1 > exp

dd count=1 if=fifo > out &
(echo 1; sleep .5; echo 2) | cat -v > fifo
wait # for dd to complete

# Though unlikely, this test may fail because dd was starved
# between opening the fifo and reading from it until after the
# second echo.  So ask to double check rather than failing.
compare out exp || skip_test_ "possible test failure. Please verify."

Exit $fail
