#!/bin/sh
# exercise chcon

if test "$VERBOSE" = yes; then
  set -x
  chcon --version
fi

. $srcdir/../lang-default
PRIV_CHECK_ARG=require-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir -p d/sub/s2 || framework_failure=1
touch f g d/sub/1 d/sub/2 || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# Set to a specified context.
u1=root
r1=object_r
t1=tmp_t
ctx=$u1:$r1:$t1
chcon $ctx f || fail=1
stat --printf='f|%C\n' f > out || fail=1

# Use --reference.
chcon --ref=f g || fail=1
stat --printf='g|%C\n' g >> out || fail=1

# Change the individual parts of the context, one by one.
u2=user_u
r2=object_r
t2=file_t
l2=SystemLow-SystemHigh
for i in --user=$u2 --role=$r2 --type=$t2 --range=$l2; do
  chcon $i f || fail=1
  stat --printf="f|$i|"'%C\n' f >> out || fail=1
done

# Same, but change back using the short-named options.
for i in -u$u1 -r$r1 -t$t1; do
  chcon $i f || fail=1
  stat --printf="f|$i|"'%C\n' f >> out || fail=1
done

cat <<EOF > exp || fail=1
f|$ctx
g|$ctx
f|--user=$u2|$u2:$r1:$t1
f|--role=$r2|$u2:$r2:$t1
f|--type=$t2|$u2:$r2:$t2
f|--range=$l2|$u2:$r2:$t2:$l2
f|-uroot|root:object_r:file_t:SystemLow-SystemHigh
f|-robject_r|root:object_r:file_t:SystemLow-SystemHigh
f|-ttmp_t|root:object_r:tmp_t:SystemLow-SystemHigh
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
