#!/bin/sh
# ensure that pathchk exits nonzero in one particular case where it didn't

if test "$VERBOSE" = yes; then
  set -x
  pathchk --version
fi

PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
touch file || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

# This should exit nonzero.  Before 2.0.13, it gave a diagnostic,
# but exited successfully.
pathchk file/x > /dev/null 2>&1 && fail=1

(exit $fail); exit
