#!/bin/sh
# basic tests for printf

prog=`pwd`/../../src/printf

if test "$VERBOSE" = yes; then
  set -x
  $prog --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# This would fail (by printing the `--') for printf in sh-utils
# and in coreutils 4.5.1.
$prog -- 'foo\n' > out || fail=1
cat <<\EOF > exp
foo
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

rm -f out exp
# Until coreutils-4.5.10, this would elicit a segfault.
$prog '%*sy\n' -3 x > out || fail=1
cat <<\EOF > exp
x  y
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
