#!/bin/sh
# make sure that only two hex. digits are consumed in a \xHHH sequence

# Copyright (C) 2002, 2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prog="$abs_top_builddir/src/printf"

if test "$VERBOSE" = yes; then
  set -x
  "$prog" --version
fi

. $srcdir/test-lib.sh


fail=0

"$prog" '\x7e3\n' > out || fail=1
cat <<\EOF > exp
~3
EOF

compare out exp || fail=1

Exit $fail
