#!/bin/sh
# Test SELinux-related options.

if test "$VERBOSE" = yes; then
  set -x
  chcon --version
  cp --version
  ls --version
  mv --version
  stat --version
fi

. $srcdir/test-lib.sh
require_root_
require_selinux_
skip_if_mcstransd_is_running_

# Create a regular file, dir, fifo.
touch f || framework_failure
mkdir d s1 s2 || framework_failure
mkfifo p || framework_failure

fail=0

# special context that works both with and without mcstransd
ctx=root:object_r:tmp_t:s0

chcon $ctx f d p ||
  skip_test_ '"chcon '$ctx' ..." failed'

# inspect that context with both ls -Z and stat.
for i in d f p; do
  c=`ls -dogZ $i|cut -d' ' -f3`; test x$c = x$ctx || fail=1
  c=`stat --printf %C $i`; test x$c = x$ctx || fail=1
done

# ensure that ls -l output includes the ".".
c=`ls -l f|cut -c11`; test "$c" = . || fail=1

# Copy each to a new directory and ensure that context is preserved.
cp -r --preserve=all d f p s1 || fail=1
for i in d f p; do
  c=`stat --printf %C s1/$i`; test x$c = x$ctx || fail=1
done

# Now, move each to a new directory and ensure that context is preserved.
mv d f p s2 || fail=1
for i in d f p; do
  c=`stat --printf %C s2/$i`; test x$c = x$ctx || fail=1
done

Exit $fail
