#!/bin/sh
# Test SELinux-related options.

# Copyright (C) 2007-2010 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  chcon --version
  cp --version
  ls --version
  mv --version
  stat --version
fi

. $srcdir/test-lib.sh
require_root_
require_selinux_
skip_if_mcstransd_is_running_

# Create a regular file, dir, fifo.
touch f || framework_failure
mkdir d s1 s2 || framework_failure
mkfifo p || framework_failure


# special context that works both with and without mcstransd
ctx=root:object_r:tmp_t:s0

chcon $ctx f d p ||
  skip_test_ '"chcon '$ctx' ..." failed'

# inspect that context with both ls -Z and stat.
for i in d f p; do
  c=`ls -dogZ $i|cut -d' ' -f3`; test x$c = x$ctx || fail=1
  c=`stat --printf %C $i`; test x$c = x$ctx || fail=1
done

# ensure that ls -l output includes the ".".
c=`ls -l f|cut -c11`; test "$c" = . || fail=1

# Copy each to a new directory and ensure that context is preserved.
cp -r --preserve=all d f p s1 || fail=1
for i in d f p; do
  c=`stat --printf %C s1/$i`; test x$c = x$ctx || fail=1
done

# Now, move each to a new directory and ensure that context is preserved.
mv d f p s2 || fail=1
for i in d f p; do
  c=`stat --printf %C s2/$i`; test x$c = x$ctx || fail=1
done

Exit $fail
