#!/bin/bash
# Tests for file descriptor exhaustion.

# Copyright (C) 2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  sort --version
fi

. $srcdir/test-lib.sh

# Skip the test when running under valgrind.
( ulimit -n 6; sort < /dev/null ) \
  || skip_test_ 'fd-limited sort failed; are you running under valgrind?'

for i in $(seq 31); do
  echo $i | tee -a in > __test.$i || framework_failure
done

fail=0

(
 ulimit -n 6
 exec 0</dev/null 3<&- 4<&- 5<&-
 sort -n -m __test.* > out
) &&
compare in out || { fail=1; echo 'file descriptor exhaustion not handled' 1>&2; }

echo 32 | tee -a in > in1
(
 ulimit -n 6
 exec 3<&- 4<&- 5<&-
 sort -n -m __test.* - < in1 > out
) &&
compare in out || { fail=1; echo 'stdin not handled properly' 1>&2; }

Exit $fail
