#!/bin/sh
# exercise sort's --sort=version option

# Copyright (C) 2008 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  sort --version
fi

. $srcdir/test-lib.sh

cat > in <<- _EOF_
	string start 5.0.0 end of str
	string start 5.00.0 end of str
	string start 5.1.0 end of str
	string start 5.10.0 end of str
	string start 5.2.0 end of str
	string start 5.20.0 end of str
	string start 5.3.0 end of str
	string start 5.30.0 end of str
	string start 5.4.0 end of str
	string start 5.40.0 end of str
	string start 5.5.0 end of str
	string start 5.50.0 end of str
	string start 5.6.0 end of str
	string start 5.60.0 end of str
	string start 5.7.0 end of str
	string start 5.70.0 end of str
	string start 5.8.0 end of str
	string start 5.80.0 end of str
	string start 5.9.0 end of str
	string start 5.90.0 end of str
	_EOF_

cat > exp <<- _EOF_
	string start 5.00.0 end of str
	string start 5.0.0 end of str
	string start 5.1.0 end of str
	string start 5.2.0 end of str
	string start 5.3.0 end of str
	string start 5.4.0 end of str
	string start 5.5.0 end of str
	string start 5.6.0 end of str
	string start 5.7.0 end of str
	string start 5.8.0 end of str
	string start 5.9.0 end of str
	string start 5.10.0 end of str
	string start 5.20.0 end of str
	string start 5.30.0 end of str
	string start 5.40.0 end of str
	string start 5.50.0 end of str
	string start 5.60.0 end of str
	string start 5.70.0 end of str
	string start 5.80.0 end of str
	string start 5.90.0 end of str
	_EOF_

fail=0
sort --sort=version -o out in || fail=1
compare exp out || fail=1
Exit $fail
