#!/bin/sh
# show that `split --lines=2' works.

if test "$VERBOSE" = yes; then
  set -x
  ln --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
printf '1\n2\n3\n4\n5\n' > in || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

split --lines=2 in > out || fail=1
cat <<\EOF > exp-1
1
2
EOF
cat <<\EOF > exp-2
3
4
EOF
cat <<\EOF > exp-3
5
EOF

cmp xaa exp-1 || fail=1
test $fail = 1 && diff xaa exp 2> /dev/null
cmp xab exp-2 || fail=1
test $fail = 2 && diff xab exp 2> /dev/null
cmp xac exp-3 || fail=1
test $fail = 3 && diff xac exp 2> /dev/null
test -f xad && fail=1

(exit $fail); exit $fail
