#!/bin/sh
# split must fail when given length/count of zero.

if test "$VERBOSE" = yes; then
  set -x
  split --version
fi

. $srcdir/../lang-default

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
touch in || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

split -a 0 in 2> /dev/null || fail=1
split -b 0 in 2> /dev/null && fail=1
split -C 0 in 2> /dev/null && fail=1
split -l 0 in 2> /dev/null && fail=1

# Make sure that the obsolete -N notation still works
split -1 in 2> /dev/null || fail=1

# Then make sure that -0 evokes a failure.
split -0 in 2> /dev/null && fail=1

# Ensure that split --lines=N and --bytes=N work for N=2^32,
# assuming our host supports integers that wide.
if _4gb=`expr 4294967296 + 0 2>/dev/null`; then
  split --lines=$_4gb in || fail=1
  split --bytes=$_4gb in || fail=1
fi

# Currently (coreutils-5.0.1) split --line-bytes=M fails
# with `invalid number of bytes' for M=2^32 or larger.  Actually,
# the limit is SIZE_MAX, which is 2^32 on 32-bit systems.
# On 64-bit systems, there's no problem with a count of 2^32,
# So disable this test in order to avoid the `failure' on 64-bit systems.
#split --line-bytes=$_4gb 2> /dev/null in && fail=1

# Make sure that a huge obsolete option evokes the right failure.
split -99999999999999999991 2> out && fail=1

# On losing systems (x86 Solaris 5.9 c89), we get a message like this:
#   split: line count option -9999999999... is too large
# while on most, we get this:
#   split: line count option -99999999999999999991... is too large
# so map them both to -99*.
sed 's/99[19]*/99*/' out > out-t
mv -f out-t out

cat <<\EOF > exp
split: line count option -99*... is too large
EOF
cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null


(exit $fail); exit $fail
