#!/bin/sh
# Show that split -a works.

if test "$VERBOSE" = yes; then
  set -x
  split --version
fi

pwd=`pwd`
tmp=split-a.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# Generate a 27-byte file
# yes|tr -d y|head -n27 > in
echo abcdefghijklmnopqrstuvwxyz > in

# This should fail.
split -b 1 -a 1 in 2> err && fail=1
test -f xa || fail=1
test -f xz || fail=1
test -f xaa && fail=1
test -f xaz && fail=1
rm -f x*

# With a longer suffix, it must succeed.
split --verbose -b 1 -a 2 in 2> err || fail=1
test -f xaa || fail=1
test -f xaz || fail=1
test -f xba || fail=1
test -f xbb && fail=1

cat <<\EOF > exp
creating file `xaa'
creating file `xab'
creating file `xac'
creating file `xad'
creating file `xae'
creating file `xaf'
creating file `xag'
creating file `xah'
creating file `xai'
creating file `xaj'
creating file `xak'
creating file `xal'
creating file `xam'
creating file `xan'
creating file `xao'
creating file `xap'
creating file `xaq'
creating file `xar'
creating file `xas'
creating file `xat'
creating file `xau'
creating file `xav'
creating file `xaw'
creating file `xax'
creating file `xay'
creating file `xaz'
creating file `xba'
EOF

cmp err exp || fail=1
test $fail = 1 && diff err exp 2> /dev/null

(exit $fail); exit $fail
