#!/bin/sh
# ensure that stat properly handles a format string ending with %

if test "$VERBOSE" = yes; then
  set -x
  stat --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

for i in `seq 50`; do
  fmt=`printf "%${i}s" %`
  out=`stat --form="$fmt" .`
  test "$out" = "$fmt" || fail=1
done

(exit $fail); exit $fail
