#!/bin/sh
# Validate timeout parameter combinations

# Copyright (C) 2008-2010 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  timeout --version
fi

. $srcdir/test-lib.sh
getlimits_


# internal errors are 125, distinct from execution failure

# --help and --version must be specified alone
timeout --help --version
test $? = 125 || fail=1

# invalid timeout
timeout invalid sleep 0
test $? = 125 || fail=1

# invalid timeout suffix
timeout 42D sleep 0
test $? = 125 || fail=1

# timeout overflow
timeout $UINT_OFLOW sleep 0
test $? = 125 || fail=1

# timeout overflow
timeout $(expr $UINT_MAX / 86400 + 1)d sleep 0
test $? = 125 || fail=1

# invalid signal spec
timeout --signal=invalid 1 sleep 0
test $? = 125 || fail=1

# invalid command
timeout 10 .
test $? = 126 || fail=1

# no such command
timeout 10 no_such
test $? = 127 || fail=1

Exit $fail
