#!/bin/sh
# Make sure truncate fails for a directory.

if test "$VERBOSE" = yes; then
  set -x
  truncate --version
fi

. $srcdir/test-lib.sh

# truncate on dir not allowed
truncate -s+0 . && fail=1 || fail=0

Exit $fail
