#!/bin/sh
# Test "ln -sf".

# Copyright (C) 1997, 1998, 1999, 2000 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

test=sf-1

if test "$VERBOSE" = yes; then
  set -x
  ln --version
fi

# Make sure we get English translations.
. $srcdir/../lang-default

tmp=t-ln.$$

test_failure=0
mkdir $tmp || test_failure=1
cd $tmp || test_failure=1
echo foo > a || test_failure=1
ln -s . b || test_failure=1

if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0
ln -sf a b > err 2>&1 && fail=1
case `cat err` in
  *'are the same file') ;;
  *) fail=1 ;;
esac

cd ..
rm -rf $tmp

exit $fail
