#!/bin/sh
# Test "ln -sf".

# Copyright (C) 1997-2000, 2007-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ln --version
fi

# Make sure we get English translations.
. $srcdir/test-lib.sh

echo foo > a || framework_failure
ln -s . b || framework_failure

fail=0
ln -sf a b > err 2>&1 && fail=1
case `cat err` in
  *'are the same file') ;;
  *) fail=1 ;;
esac

Exit $fail
