#!/bin/sh
# ensure that touch f; ln -T f no-such-file/ does not mistakenly succeed

# Copyright (C) 2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ln --version
fi

. $srcdir/test-lib.sh

touch f || framework_failure

fail=0

# Before coreutils-7.6, this would succeed on Solaris 10
ln -T f no-such-file/ && fail=1
test -e no-such-file && fail=1

Exit $fail
