#! /bin/sh
# This script was generated automatically by build-script.
case $# in
  0) xx='../../src/date';;
  *) xx="$1";;
esac
test "$VERBOSE" && echo=echo || echo=:
$echo testing program: $xx
errors=0
test "$srcdir" || srcdir=.
test "$VERBOSE" && $xx --version 2> /dev/null

# Make sure we get English translations.
LANGUAGE=C
export LANGUAGE
LC_ALL=C
export LC_ALL
LANG=C
export LANG

LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%% %a %A %b %B'  > 1.O 2> 1.E
code=$?
if test $code != 0 ; then
  $echo "Test 1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 1.O $srcdir/1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 1(LANG=C TZ=UTC) failed: files 1.O and $srcdir/1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 1.O $srcdir/1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 1.E || rm -f 1.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%c'  > 2.O 2> 2.E
code=$?
if test $code != 0 ; then
  $echo "Test 2(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 2.O $srcdir/2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 2(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 2(LANG=C TZ=UTC) failed: files 2.O and $srcdir/2.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 2(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 2.O $srcdir/2.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 2.E || rm -f 2.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%d_%D_%e_%h_%H'  > 3.O 2> 3.E
code=$?
if test $code != 0 ; then
  $echo "Test 3(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 3.O $srcdir/3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 3(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 3(LANG=C TZ=UTC) failed: files 3.O and $srcdir/3.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 3(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 3.O $srcdir/3.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 3.E || rm -f 3.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%I_%j_%k_%l_%m'  > 4.O 2> 4.E
code=$?
if test $code != 0 ; then
  $echo "Test 4(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 4.O $srcdir/4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 4(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 4(LANG=C TZ=UTC) failed: files 4.O and $srcdir/4.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 4(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 4.O $srcdir/4.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 4.E || rm -f 4.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%M_%n_%p_%r'  > 5.O 2> 5.E
code=$?
if test $code != 0 ; then
  $echo "Test 5(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 5.O $srcdir/5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 5(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 5(LANG=C TZ=UTC) failed: files 5.O and $srcdir/5.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 5(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 5.O $srcdir/5.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 5.E || rm -f 5.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%s_%S_%t_%T'  > 6.O 2> 6.E
code=$?
if test $code != 0 ; then
  $echo "Test 6(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 6.O $srcdir/6.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 6(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 6(LANG=C TZ=UTC) failed: files 6.O and $srcdir/6.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 6(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 6.O $srcdir/6.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 6.E || rm -f 6.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%U_%V_%w_%W'  > 7.O 2> 7.E
code=$?
if test $code != 0 ; then
  $echo "Test 7(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 7.O $srcdir/7.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 7(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 7(LANG=C TZ=UTC) failed: files 7.O and $srcdir/7.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 7(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 7.O $srcdir/7.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 7.E || rm -f 7.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%x_%X_%y_%Y'  > 8.O 2> 8.E
code=$?
if test $code != 0 ; then
  $echo "Test 8(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 8.O $srcdir/8.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 8(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 8(LANG=C TZ=UTC) failed: files 8.O and $srcdir/8.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 8(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 8.O $srcdir/8.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 8.E || rm -f 8.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0' +'%z'  > 9.O 2> 9.E
code=$?
if test $code != 0 ; then
  $echo "Test 9(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp 9.O $srcdir/9.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed 9(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test 9(LANG=C TZ=UTC) failed: files 9.O and $srcdir/9.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test 9(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp 9.O $srcdir/9.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s 9.E || rm -f 9.E
LANG=C TZ=UTC $xx --date '02/29/1996 1 year' +%Y-%m-%d  > leap-1.O 2> leap-1.E
code=$?
if test $code != 0 ; then
  $echo "Test leap-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp leap-1.O $srcdir/leap-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed leap-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test leap-1(LANG=C TZ=UTC) failed: files leap-1.O and $srcdir/leap-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test leap-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp leap-1.O $srcdir/leap-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s leap-1.E || rm -f leap-1.E
LANG=C TZ=UTC $xx --date '1995-1-1' +%U  > U95-1.O 2> U95-1.E
code=$?
if test $code != 0 ; then
  $echo "Test U95-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U95-1.O $srcdir/U95-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U95-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U95-1(LANG=C TZ=UTC) failed: files U95-1.O and $srcdir/U95-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U95-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U95-1.O $srcdir/U95-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U95-1.E || rm -f U95-1.E
LANG=C TZ=UTC $xx --date '1995-1-7' +%U  > U95-2.O 2> U95-2.E
code=$?
if test $code != 0 ; then
  $echo "Test U95-2(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U95-2.O $srcdir/U95-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U95-2(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U95-2(LANG=C TZ=UTC) failed: files U95-2.O and $srcdir/U95-2.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U95-2(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U95-2.O $srcdir/U95-2.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U95-2.E || rm -f U95-2.E
LANG=C TZ=UTC $xx --date '1995-1-8' +%U  > U95-3.O 2> U95-3.E
code=$?
if test $code != 0 ; then
  $echo "Test U95-3(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U95-3.O $srcdir/U95-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U95-3(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U95-3(LANG=C TZ=UTC) failed: files U95-3.O and $srcdir/U95-3.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U95-3(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U95-3.O $srcdir/U95-3.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U95-3.E || rm -f U95-3.E
LANG=C TZ=UTC $xx --date '1992-1-1' +%U  > U92-1.O 2> U92-1.E
code=$?
if test $code != 0 ; then
  $echo "Test U92-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U92-1.O $srcdir/U92-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U92-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U92-1(LANG=C TZ=UTC) failed: files U92-1.O and $srcdir/U92-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U92-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U92-1.O $srcdir/U92-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U92-1.E || rm -f U92-1.E
LANG=C TZ=UTC $xx --date '1992-1-4' +%U  > U92-2.O 2> U92-2.E
code=$?
if test $code != 0 ; then
  $echo "Test U92-2(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U92-2.O $srcdir/U92-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U92-2(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U92-2(LANG=C TZ=UTC) failed: files U92-2.O and $srcdir/U92-2.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U92-2(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U92-2.O $srcdir/U92-2.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U92-2.E || rm -f U92-2.E
LANG=C TZ=UTC $xx --date '1992-1-5' +%U  > U92-3.O 2> U92-3.E
code=$?
if test $code != 0 ; then
  $echo "Test U92-3(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp U92-3.O $srcdir/U92-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed U92-3(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test U92-3(LANG=C TZ=UTC) failed: files U92-3.O and $srcdir/U92-3.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test U92-3(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp U92-3.O $srcdir/U92-3.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s U92-3.E || rm -f U92-3.E
LANG=C TZ=UTC $xx --date '1992-1-1' +%V  > V92-1.O 2> V92-1.E
code=$?
if test $code != 0 ; then
  $echo "Test V92-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp V92-1.O $srcdir/V92-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed V92-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test V92-1(LANG=C TZ=UTC) failed: files V92-1.O and $srcdir/V92-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test V92-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp V92-1.O $srcdir/V92-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s V92-1.E || rm -f V92-1.E
LANG=C TZ=UTC $xx --date '1992-1-5' +%V  > V92-2.O 2> V92-2.E
code=$?
if test $code != 0 ; then
  $echo "Test V92-2(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp V92-2.O $srcdir/V92-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed V92-2(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test V92-2(LANG=C TZ=UTC) failed: files V92-2.O and $srcdir/V92-2.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test V92-2(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp V92-2.O $srcdir/V92-2.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s V92-2.E || rm -f V92-2.E
LANG=C TZ=UTC $xx --date '1992-1-6' +%V  > V92-3.O 2> V92-3.E
code=$?
if test $code != 0 ; then
  $echo "Test V92-3(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp V92-3.O $srcdir/V92-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed V92-3(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test V92-3(LANG=C TZ=UTC) failed: files V92-3.O and $srcdir/V92-3.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test V92-3(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp V92-3.O $srcdir/V92-3.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s V92-3.E || rm -f V92-3.E
LANG=C TZ=UTC $xx --date '1992-1-1' +%W  > W92-1.O 2> W92-1.E
code=$?
if test $code != 0 ; then
  $echo "Test W92-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp W92-1.O $srcdir/W92-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed W92-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test W92-1(LANG=C TZ=UTC) failed: files W92-1.O and $srcdir/W92-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test W92-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp W92-1.O $srcdir/W92-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s W92-1.E || rm -f W92-1.E
LANG=C TZ=UTC $xx --date '1992-1-5' +%W  > W92-2.O 2> W92-2.E
code=$?
if test $code != 0 ; then
  $echo "Test W92-2(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp W92-2.O $srcdir/W92-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed W92-2(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test W92-2(LANG=C TZ=UTC) failed: files W92-2.O and $srcdir/W92-2.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test W92-2(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp W92-2.O $srcdir/W92-2.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s W92-2.E || rm -f W92-2.E
LANG=C TZ=UTC $xx --date '1992-1-6' +%W  > W92-3.O 2> W92-3.E
code=$?
if test $code != 0 ; then
  $echo "Test W92-3(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp W92-3.O $srcdir/W92-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed W92-3(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test W92-3(LANG=C TZ=UTC) failed: files W92-3.O and $srcdir/W92-3.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test W92-3(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp W92-3.O $srcdir/W92-3.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s W92-3.E || rm -f W92-3.E
LANG=C TZ=UTC $xx --date '1998-1-1 3 years' +%Y  > millen-1.O 2> millen-1.E
code=$?
if test $code != 0 ; then
  $echo "Test millen-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp millen-1.O $srcdir/millen-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed millen-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test millen-1(LANG=C TZ=UTC) failed: files millen-1.O and $srcdir/millen-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test millen-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp millen-1.O $srcdir/millen-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s millen-1.E || rm -f millen-1.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 now' '+%Y-%m-%d %T'  > rel-0.O 2> rel-0.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-0(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-0.O $srcdir/rel-0.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-0(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-0(LANG=C TZ=UTC) failed: files rel-0.O and $srcdir/rel-0.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-0(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-0.O $srcdir/rel-0.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-0.E || rm -f rel-0.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 yesterday' '+%Y-%m-%d %T'  > rel-1a.O 2> rel-1a.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-1a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-1a.O $srcdir/rel-1a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-1a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-1a(LANG=C TZ=UTC) failed: files rel-1a.O and $srcdir/rel-1a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-1a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-1a.O $srcdir/rel-1a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-1a.E || rm -f rel-1a.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 tomorrow' '+%Y-%m-%d %T'  > rel-1b.O 2> rel-1b.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-1b(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-1b.O $srcdir/rel-1b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-1b(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-1b(LANG=C TZ=UTC) failed: files rel-1b.O and $srcdir/rel-1b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-1b(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-1b.O $srcdir/rel-1b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-1b.E || rm -f rel-1b.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 6 years ago' '+%Y-%m-%d %T'  > rel-2a.O 2> rel-2a.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2a.O $srcdir/rel-2a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2a(LANG=C TZ=UTC) failed: files rel-2a.O and $srcdir/rel-2a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2a.O $srcdir/rel-2a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2a.E || rm -f rel-2a.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 7 months ago' '+%Y-%m-%d %T'  > rel-2b.O 2> rel-2b.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2b(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2b.O $srcdir/rel-2b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2b(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2b(LANG=C TZ=UTC) failed: files rel-2b.O and $srcdir/rel-2b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2b(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2b.O $srcdir/rel-2b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2b.E || rm -f rel-2b.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 8 weeks ago' '+%Y-%m-%d %T'  > rel-2c.O 2> rel-2c.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2c(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2c.O $srcdir/rel-2c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2c(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2c(LANG=C TZ=UTC) failed: files rel-2c.O and $srcdir/rel-2c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2c(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2c.O $srcdir/rel-2c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2c.E || rm -f rel-2c.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 1 day ago' '+%Y-%m-%d %T'  > rel-2d.O 2> rel-2d.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2d(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2d.O $srcdir/rel-2d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2d(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2d(LANG=C TZ=UTC) failed: files rel-2d.O and $srcdir/rel-2d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2d(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2d.O $srcdir/rel-2d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2d.E || rm -f rel-2d.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 2 hours ago' '+%Y-%m-%d %T'  > rel-2e.O 2> rel-2e.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2e(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2e.O $srcdir/rel-2e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2e(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2e(LANG=C TZ=UTC) failed: files rel-2e.O and $srcdir/rel-2e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2e(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2e.O $srcdir/rel-2e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2e.E || rm -f rel-2e.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 3 minutes ago' '+%Y-%m-%d %T'  > rel-2f.O 2> rel-2f.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2f(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2f.O $srcdir/rel-2f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2f(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2f(LANG=C TZ=UTC) failed: files rel-2f.O and $srcdir/rel-2f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2f(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2f.O $srcdir/rel-2f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2f.E || rm -f rel-2f.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 4 seconds ago' '+%Y-%m-%d %T'  > rel-2g.O 2> rel-2g.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-2g(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-2g.O $srcdir/rel-2g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-2g(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-2g(LANG=C TZ=UTC) failed: files rel-2g.O and $srcdir/rel-2g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-2g(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-2g.O $srcdir/rel-2g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-2g.E || rm -f rel-2g.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 4 seconds ago' '+%Y-%m-%d %T'  > rel-3a.O 2> rel-3a.E
code=$?
if test $code != 0 ; then
  $echo "Test rel-3a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp rel-3a.O $srcdir/rel-3a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed rel-3a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test rel-3a(LANG=C TZ=UTC) failed: files rel-3a.O and $srcdir/rel-3a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test rel-3a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp rel-3a.O $srcdir/rel-3a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s rel-3a.E || rm -f rel-3a.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next second' '+%Y-%m-%d %T'  > next-s.O 2> next-s.E
code=$?
if test $code != 0 ; then
  $echo "Test next-s(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-s.O $srcdir/next-s.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-s(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-s(LANG=C TZ=UTC) failed: files next-s.O and $srcdir/next-s.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-s(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-s.O $srcdir/next-s.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-s.E || rm -f next-s.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next minute' '+%Y-%m-%d %T'  > next-m.O 2> next-m.E
code=$?
if test $code != 0 ; then
  $echo "Test next-m(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-m.O $srcdir/next-m.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-m(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-m(LANG=C TZ=UTC) failed: files next-m.O and $srcdir/next-m.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-m(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-m.O $srcdir/next-m.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-m.E || rm -f next-m.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next hour'   '+%Y-%m-%d %T'  > next-h.O 2> next-h.E
code=$?
if test $code != 0 ; then
  $echo "Test next-h(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-h.O $srcdir/next-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-h(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-h(LANG=C TZ=UTC) failed: files next-h.O and $srcdir/next-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-h(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-h.O $srcdir/next-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-h.E || rm -f next-h.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next day'    '+%Y-%m-%d %T'  > next-d.O 2> next-d.E
code=$?
if test $code != 0 ; then
  $echo "Test next-d(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-d.O $srcdir/next-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-d(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-d(LANG=C TZ=UTC) failed: files next-d.O and $srcdir/next-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-d(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-d.O $srcdir/next-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-d.E || rm -f next-d.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next week'   '+%Y-%m-%d %T'  > next-w.O 2> next-w.E
code=$?
if test $code != 0 ; then
  $echo "Test next-w(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-w.O $srcdir/next-w.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-w(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-w(LANG=C TZ=UTC) failed: files next-w.O and $srcdir/next-w.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-w(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-w.O $srcdir/next-w.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-w.E || rm -f next-w.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next month' '+%Y-%m-%d %T'  > next-mo.O 2> next-mo.E
code=$?
if test $code != 0 ; then
  $echo "Test next-mo(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-mo.O $srcdir/next-mo.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-mo(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-mo(LANG=C TZ=UTC) failed: files next-mo.O and $srcdir/next-mo.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-mo(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-mo.O $srcdir/next-mo.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-mo.E || rm -f next-mo.E
LANG=C TZ=UTC $xx -d '1997-01-19 08:17:48 +0 next year'   '+%Y-%m-%d %T'  > next-y.O 2> next-y.E
code=$?
if test $code != 0 ; then
  $echo "Test next-y(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp next-y.O $srcdir/next-y.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed next-y(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test next-y(LANG=C TZ=UTC) failed: files next-y.O and $srcdir/next-y.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test next-y(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp next-y.O $srcdir/next-y.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s next-y.E || rm -f next-y.E
TZ=UTC+4 $xx -u -d '08/01/97 6:00' '+%D,%H:%M'  > utc-0.O 2> utc-0.E
code=$?
if test $code != 0 ; then
  $echo "Test utc-0(TZ=UTC+4) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp utc-0.O $srcdir/utc-0.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed utc-0(TZ=UTC+4)"; fi ;;
    1) $echo "Test utc-0(TZ=UTC+4) failed: files utc-0.O and $srcdir/utc-0.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test utc-0(TZ=UTC+4) may have failed." 1>&2;
       $echo The command "cmp utc-0.O $srcdir/utc-0.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s utc-0.E || rm -f utc-0.E
LANG=C TZ=UTC $xx -u -d '08/01/97 6:00 UTC +4 hours' '+%D,%H:%M'  > utc-0a.O 2> utc-0a.E
code=$?
if test $code != 0 ; then
  $echo "Test utc-0a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp utc-0a.O $srcdir/utc-0a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed utc-0a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test utc-0a(LANG=C TZ=UTC) failed: files utc-0a.O and $srcdir/utc-0a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test utc-0a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp utc-0a.O $srcdir/utc-0a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s utc-0a.E || rm -f utc-0a.E
TZ=UTC+1 $xx -u --file=- '+%Y-%m-%d %T' < $srcdir/utc-1.I > utc-1.O 2> utc-1.E
code=$?
if test $code != 0 ; then
  $echo "Test utc-1(TZ=UTC+1) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp utc-1.O $srcdir/utc-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed utc-1(TZ=UTC+1)"; fi ;;
    1) $echo "Test utc-1(TZ=UTC+1) failed: files utc-1.O and $srcdir/utc-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test utc-1(TZ=UTC+1) may have failed." 1>&2;
       $echo The command "cmp utc-1.O $srcdir/utc-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s utc-1.E || rm -f utc-1.E
LANG=C TZ=UTC $xx -u --file=- '+%Y-%m-%d %T' < $srcdir/utc-1a.I > utc-1a.O 2> utc-1a.E
code=$?
if test $code != 0 ; then
  $echo "Test utc-1a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp utc-1a.O $srcdir/utc-1a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed utc-1a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test utc-1a(LANG=C TZ=UTC) failed: files utc-1a.O and $srcdir/utc-1a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test utc-1a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp utc-1a.O $srcdir/utc-1a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s utc-1a.E || rm -f utc-1a.E
TZ=UTC+2 $xx -d '1970-01-01 00:00:01' +%s  > date2sec-0.O 2> date2sec-0.E
code=$?
if test $code != 0 ; then
  $echo "Test date2sec-0(TZ=UTC+2) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp date2sec-0.O $srcdir/date2sec-0.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed date2sec-0(TZ=UTC+2)"; fi ;;
    1) $echo "Test date2sec-0(TZ=UTC+2) failed: files date2sec-0.O and $srcdir/date2sec-0.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test date2sec-0(TZ=UTC+2) may have failed." 1>&2;
       $echo The command "cmp date2sec-0.O $srcdir/date2sec-0.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s date2sec-0.E || rm -f date2sec-0.E
LANG=C TZ=UTC $xx -d '1970-01-01 00:00:01 UTC +2 hours' +%s  > date2sec-0a.O 2> date2sec-0a.E
code=$?
if test $code != 0 ; then
  $echo "Test date2sec-0a(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp date2sec-0a.O $srcdir/date2sec-0a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed date2sec-0a(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test date2sec-0a(LANG=C TZ=UTC) failed: files date2sec-0a.O and $srcdir/date2sec-0a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test date2sec-0a(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp date2sec-0a.O $srcdir/date2sec-0a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s date2sec-0a.E || rm -f date2sec-0a.E
LANG=C TZ=UTC $xx -d 2000-01-01 +%s  > date2sec-1.O 2> date2sec-1.E
code=$?
if test $code != 0 ; then
  $echo "Test date2sec-1(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp date2sec-1.O $srcdir/date2sec-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed date2sec-1(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test date2sec-1(LANG=C TZ=UTC) failed: files date2sec-1.O and $srcdir/date2sec-1.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test date2sec-1(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp date2sec-1.O $srcdir/date2sec-1.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s date2sec-1.E || rm -f date2sec-1.E
LANG=C TZ=UTC $xx -d '1970-01-01 UTC 946684800 sec' +'%Y-%m-%d %T %z'  > sec2date-0.O 2> sec2date-0.E
code=$?
if test $code != 0 ; then
  $echo "Test sec2date-0(LANG=C TZ=UTC) failed: ../../src/date return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp sec2date-0.O $srcdir/sec2date-0.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed sec2date-0(LANG=C TZ=UTC)"; fi ;;
    1) $echo "Test sec2date-0(LANG=C TZ=UTC) failed: files sec2date-0.O and $srcdir/sec2date-0.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test sec2date-0(LANG=C TZ=UTC) may have failed." 1>&2;
       $echo The command "cmp sec2date-0.O $srcdir/sec2date-0.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s sec2date-0.E || rm -f sec2date-0.E
if test $errors = 0 ; then
  $echo Passed all 49 tests. 1>&2
else
  $echo Failed $errors tests. 1>&2
fi
test $errors = 0 || errors=1
exit $errors
