#!/bin/sh
# test for "tee -".

if test "$VERBOSE" = yes; then
  set -x
  tee --version
fi

pwd=`pwd`
t0=`echo "$0" |sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap 'status=$?; (exit $status); exit $status' 1 2 13 15

fail=0
mkdir -p $tmp && cd $tmp || fail=1

if test $fail = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

tee - </dev/null || fail=1

(exit $fail); exit $fail
