#! /bin/sh
# This script was generated automatically by mk-script.
case $# in
  0) xx='../../src/tail';;
  *) xx="$1";;
esac
test "$VERBOSE" && echo=echo || echo=:
$echo testing program: $xx
errors=0
test "$srcdir" || srcdir=.
test "$VERBOSE" && $xx --version 2> /dev/null

# Make sure we get English translations.
LANGUAGE=C
export LANGUAGE
LC_ALL=C
export LC_ALL
LANG=C
export LANG

_POSIX2_VERSION=199209 $xx +2c $srcdir/obs-c1.I > obs-c1.O 2> obs-c1.E
code=$?
if test $code != 0; then
  $echo "Test obs-c1(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c1.O $srcdir/obs-c1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c1(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-c1(_POSIX2_VERSION=199209:F) failed: files obs-c1.O and $srcdir/obs-c1.X differ" 1>&2
       (diff -c obs-c1.O $srcdir/obs-c1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c1(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-c1.O $srcdir/obs-c1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c1.E || rm -f obs-c1.E
cat $srcdir/obs-c1.I | _POSIX2_VERSION=199209 $xx +2c > obs-c1.O 2> obs-c1.E
code=$?
if test $code != 0; then
  $echo "Test obs-c1(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c1.O $srcdir/obs-c1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c1(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-c1(_POSIX2_VERSION=199209:|) failed: files obs-c1.O and $srcdir/obs-c1.X differ" 1>&2
       (diff -c obs-c1.O $srcdir/obs-c1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c1(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-c1.O $srcdir/obs-c1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c1.E || rm -f obs-c1.E
_POSIX2_VERSION=199209 $xx +2c < $srcdir/obs-c1.I > obs-c1.O 2> obs-c1.E
code=$?
if test $code != 0; then
  $echo "Test obs-c1(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c1.O $srcdir/obs-c1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c1(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-c1(_POSIX2_VERSION=199209:<) failed: files obs-c1.O and $srcdir/obs-c1.X differ" 1>&2
       (diff -c obs-c1.O $srcdir/obs-c1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c1(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-c1.O $srcdir/obs-c1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c1.E || rm -f obs-c1.E
_POSIX2_VERSION=199209 $xx +8c $srcdir/obs-c2.I > obs-c2.O 2> obs-c2.E
code=$?
if test $code != 0; then
  $echo "Test obs-c2(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c2.O $srcdir/obs-c2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c2(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-c2(_POSIX2_VERSION=199209:F) failed: files obs-c2.O and $srcdir/obs-c2.X differ" 1>&2
       (diff -c obs-c2.O $srcdir/obs-c2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c2(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-c2.O $srcdir/obs-c2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c2.E || rm -f obs-c2.E
cat $srcdir/obs-c2.I | _POSIX2_VERSION=199209 $xx +8c > obs-c2.O 2> obs-c2.E
code=$?
if test $code != 0; then
  $echo "Test obs-c2(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c2.O $srcdir/obs-c2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c2(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-c2(_POSIX2_VERSION=199209:|) failed: files obs-c2.O and $srcdir/obs-c2.X differ" 1>&2
       (diff -c obs-c2.O $srcdir/obs-c2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c2(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-c2.O $srcdir/obs-c2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c2.E || rm -f obs-c2.E
_POSIX2_VERSION=199209 $xx +8c < $srcdir/obs-c2.I > obs-c2.O 2> obs-c2.E
code=$?
if test $code != 0; then
  $echo "Test obs-c2(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c2.O $srcdir/obs-c2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c2(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-c2(_POSIX2_VERSION=199209:<) failed: files obs-c2.O and $srcdir/obs-c2.X differ" 1>&2
       (diff -c obs-c2.O $srcdir/obs-c2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c2(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-c2.O $srcdir/obs-c2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c2.E || rm -f obs-c2.E
_POSIX2_VERSION=199209 $xx -1c $srcdir/obs-c3.I > obs-c3.O 2> obs-c3.E
code=$?
if test $code != 0; then
  $echo "Test obs-c3(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c3.O $srcdir/obs-c3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c3(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-c3(_POSIX2_VERSION=199209:F) failed: files obs-c3.O and $srcdir/obs-c3.X differ" 1>&2
       (diff -c obs-c3.O $srcdir/obs-c3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c3(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-c3.O $srcdir/obs-c3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c3.E || rm -f obs-c3.E
cat $srcdir/obs-c3.I | _POSIX2_VERSION=199209 $xx -1c > obs-c3.O 2> obs-c3.E
code=$?
if test $code != 0; then
  $echo "Test obs-c3(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c3.O $srcdir/obs-c3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c3(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-c3(_POSIX2_VERSION=199209:|) failed: files obs-c3.O and $srcdir/obs-c3.X differ" 1>&2
       (diff -c obs-c3.O $srcdir/obs-c3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c3(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-c3.O $srcdir/obs-c3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c3.E || rm -f obs-c3.E
_POSIX2_VERSION=199209 $xx -1c < $srcdir/obs-c3.I > obs-c3.O 2> obs-c3.E
code=$?
if test $code != 0; then
  $echo "Test obs-c3(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c3.O $srcdir/obs-c3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c3(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-c3(_POSIX2_VERSION=199209:<) failed: files obs-c3.O and $srcdir/obs-c3.X differ" 1>&2
       (diff -c obs-c3.O $srcdir/obs-c3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c3(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-c3.O $srcdir/obs-c3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c3.E || rm -f obs-c3.E
_POSIX2_VERSION=199209 $xx -9c $srcdir/obs-c4.I > obs-c4.O 2> obs-c4.E
code=$?
if test $code != 0; then
  $echo "Test obs-c4(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c4.O $srcdir/obs-c4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c4(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-c4(_POSIX2_VERSION=199209:F) failed: files obs-c4.O and $srcdir/obs-c4.X differ" 1>&2
       (diff -c obs-c4.O $srcdir/obs-c4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c4(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-c4.O $srcdir/obs-c4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c4.E || rm -f obs-c4.E
cat $srcdir/obs-c4.I | _POSIX2_VERSION=199209 $xx -9c > obs-c4.O 2> obs-c4.E
code=$?
if test $code != 0; then
  $echo "Test obs-c4(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c4.O $srcdir/obs-c4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c4(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-c4(_POSIX2_VERSION=199209:|) failed: files obs-c4.O and $srcdir/obs-c4.X differ" 1>&2
       (diff -c obs-c4.O $srcdir/obs-c4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c4(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-c4.O $srcdir/obs-c4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c4.E || rm -f obs-c4.E
_POSIX2_VERSION=199209 $xx -9c < $srcdir/obs-c4.I > obs-c4.O 2> obs-c4.E
code=$?
if test $code != 0; then
  $echo "Test obs-c4(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c4.O $srcdir/obs-c4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c4(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-c4(_POSIX2_VERSION=199209:<) failed: files obs-c4.O and $srcdir/obs-c4.X differ" 1>&2
       (diff -c obs-c4.O $srcdir/obs-c4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c4(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-c4.O $srcdir/obs-c4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c4.E || rm -f obs-c4.E
_POSIX2_VERSION=199209 $xx -12c $srcdir/obs-c5.I > obs-c5.O 2> obs-c5.E
code=$?
if test $code != 0; then
  $echo "Test obs-c5(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c5.O $srcdir/obs-c5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c5(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-c5(_POSIX2_VERSION=199209:F) failed: files obs-c5.O and $srcdir/obs-c5.X differ" 1>&2
       (diff -c obs-c5.O $srcdir/obs-c5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c5(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-c5.O $srcdir/obs-c5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c5.E || rm -f obs-c5.E
cat $srcdir/obs-c5.I | _POSIX2_VERSION=199209 $xx -12c > obs-c5.O 2> obs-c5.E
code=$?
if test $code != 0; then
  $echo "Test obs-c5(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c5.O $srcdir/obs-c5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c5(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-c5(_POSIX2_VERSION=199209:|) failed: files obs-c5.O and $srcdir/obs-c5.X differ" 1>&2
       (diff -c obs-c5.O $srcdir/obs-c5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c5(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-c5.O $srcdir/obs-c5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c5.E || rm -f obs-c5.E
_POSIX2_VERSION=199209 $xx -12c < $srcdir/obs-c5.I > obs-c5.O 2> obs-c5.E
code=$?
if test $code != 0; then
  $echo "Test obs-c5(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-c5.O $srcdir/obs-c5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-c5(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-c5(_POSIX2_VERSION=199209:<) failed: files obs-c5.O and $srcdir/obs-c5.X differ" 1>&2
       (diff -c obs-c5.O $srcdir/obs-c5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-c5(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-c5.O $srcdir/obs-c5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-c5.E || rm -f obs-c5.E
_POSIX2_VERSION=199209 $xx -1l $srcdir/obs-l1.I > obs-l1.O 2> obs-l1.E
code=$?
if test $code != 0; then
  $echo "Test obs-l1(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l1.O $srcdir/obs-l1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l1(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l1(_POSIX2_VERSION=199209:F) failed: files obs-l1.O and $srcdir/obs-l1.X differ" 1>&2
       (diff -c obs-l1.O $srcdir/obs-l1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l1(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l1.O $srcdir/obs-l1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l1.E || rm -f obs-l1.E
cat $srcdir/obs-l1.I | _POSIX2_VERSION=199209 $xx -1l > obs-l1.O 2> obs-l1.E
code=$?
if test $code != 0; then
  $echo "Test obs-l1(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l1.O $srcdir/obs-l1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l1(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l1(_POSIX2_VERSION=199209:|) failed: files obs-l1.O and $srcdir/obs-l1.X differ" 1>&2
       (diff -c obs-l1.O $srcdir/obs-l1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l1(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l1.O $srcdir/obs-l1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l1.E || rm -f obs-l1.E
_POSIX2_VERSION=199209 $xx -1l < $srcdir/obs-l1.I > obs-l1.O 2> obs-l1.E
code=$?
if test $code != 0; then
  $echo "Test obs-l1(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l1.O $srcdir/obs-l1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l1(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l1(_POSIX2_VERSION=199209:<) failed: files obs-l1.O and $srcdir/obs-l1.X differ" 1>&2
       (diff -c obs-l1.O $srcdir/obs-l1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l1(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l1.O $srcdir/obs-l1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l1.E || rm -f obs-l1.E
_POSIX2_VERSION=199209 $xx -1l $srcdir/obs-l2.I > obs-l2.O 2> obs-l2.E
code=$?
if test $code != 0; then
  $echo "Test obs-l2(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l2.O $srcdir/obs-l2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l2(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l2(_POSIX2_VERSION=199209:F) failed: files obs-l2.O and $srcdir/obs-l2.X differ" 1>&2
       (diff -c obs-l2.O $srcdir/obs-l2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l2(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l2.O $srcdir/obs-l2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l2.E || rm -f obs-l2.E
cat $srcdir/obs-l2.I | _POSIX2_VERSION=199209 $xx -1l > obs-l2.O 2> obs-l2.E
code=$?
if test $code != 0; then
  $echo "Test obs-l2(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l2.O $srcdir/obs-l2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l2(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l2(_POSIX2_VERSION=199209:|) failed: files obs-l2.O and $srcdir/obs-l2.X differ" 1>&2
       (diff -c obs-l2.O $srcdir/obs-l2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l2(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l2.O $srcdir/obs-l2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l2.E || rm -f obs-l2.E
_POSIX2_VERSION=199209 $xx -1l < $srcdir/obs-l2.I > obs-l2.O 2> obs-l2.E
code=$?
if test $code != 0; then
  $echo "Test obs-l2(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l2.O $srcdir/obs-l2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l2(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l2(_POSIX2_VERSION=199209:<) failed: files obs-l2.O and $srcdir/obs-l2.X differ" 1>&2
       (diff -c obs-l2.O $srcdir/obs-l2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l2(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l2.O $srcdir/obs-l2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l2.E || rm -f obs-l2.E
_POSIX2_VERSION=199209 $xx -1l $srcdir/obs-l3.I > obs-l3.O 2> obs-l3.E
code=$?
if test $code != 0; then
  $echo "Test obs-l3(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l3.O $srcdir/obs-l3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l3(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l3(_POSIX2_VERSION=199209:F) failed: files obs-l3.O and $srcdir/obs-l3.X differ" 1>&2
       (diff -c obs-l3.O $srcdir/obs-l3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l3(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l3.O $srcdir/obs-l3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l3.E || rm -f obs-l3.E
cat $srcdir/obs-l3.I | _POSIX2_VERSION=199209 $xx -1l > obs-l3.O 2> obs-l3.E
code=$?
if test $code != 0; then
  $echo "Test obs-l3(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l3.O $srcdir/obs-l3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l3(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l3(_POSIX2_VERSION=199209:|) failed: files obs-l3.O and $srcdir/obs-l3.X differ" 1>&2
       (diff -c obs-l3.O $srcdir/obs-l3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l3(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l3.O $srcdir/obs-l3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l3.E || rm -f obs-l3.E
_POSIX2_VERSION=199209 $xx -1l < $srcdir/obs-l3.I > obs-l3.O 2> obs-l3.E
code=$?
if test $code != 0; then
  $echo "Test obs-l3(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l3.O $srcdir/obs-l3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l3(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l3(_POSIX2_VERSION=199209:<) failed: files obs-l3.O and $srcdir/obs-l3.X differ" 1>&2
       (diff -c obs-l3.O $srcdir/obs-l3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l3(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l3.O $srcdir/obs-l3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l3.E || rm -f obs-l3.E
_POSIX2_VERSION=199209 $xx +1l $srcdir/obs-l4.I > obs-l4.O 2> obs-l4.E
code=$?
if test $code != 0; then
  $echo "Test obs-l4(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l4.O $srcdir/obs-l4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l4(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l4(_POSIX2_VERSION=199209:F) failed: files obs-l4.O and $srcdir/obs-l4.X differ" 1>&2
       (diff -c obs-l4.O $srcdir/obs-l4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l4(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l4.O $srcdir/obs-l4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l4.E || rm -f obs-l4.E
cat $srcdir/obs-l4.I | _POSIX2_VERSION=199209 $xx +1l > obs-l4.O 2> obs-l4.E
code=$?
if test $code != 0; then
  $echo "Test obs-l4(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l4.O $srcdir/obs-l4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l4(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l4(_POSIX2_VERSION=199209:|) failed: files obs-l4.O and $srcdir/obs-l4.X differ" 1>&2
       (diff -c obs-l4.O $srcdir/obs-l4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l4(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l4.O $srcdir/obs-l4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l4.E || rm -f obs-l4.E
_POSIX2_VERSION=199209 $xx +1l < $srcdir/obs-l4.I > obs-l4.O 2> obs-l4.E
code=$?
if test $code != 0; then
  $echo "Test obs-l4(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l4.O $srcdir/obs-l4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l4(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l4(_POSIX2_VERSION=199209:<) failed: files obs-l4.O and $srcdir/obs-l4.X differ" 1>&2
       (diff -c obs-l4.O $srcdir/obs-l4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l4(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l4.O $srcdir/obs-l4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l4.E || rm -f obs-l4.E
_POSIX2_VERSION=199209 $xx +2l $srcdir/obs-l5.I > obs-l5.O 2> obs-l5.E
code=$?
if test $code != 0; then
  $echo "Test obs-l5(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l5.O $srcdir/obs-l5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l5(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l5(_POSIX2_VERSION=199209:F) failed: files obs-l5.O and $srcdir/obs-l5.X differ" 1>&2
       (diff -c obs-l5.O $srcdir/obs-l5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l5(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l5.O $srcdir/obs-l5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l5.E || rm -f obs-l5.E
cat $srcdir/obs-l5.I | _POSIX2_VERSION=199209 $xx +2l > obs-l5.O 2> obs-l5.E
code=$?
if test $code != 0; then
  $echo "Test obs-l5(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l5.O $srcdir/obs-l5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l5(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l5(_POSIX2_VERSION=199209:|) failed: files obs-l5.O and $srcdir/obs-l5.X differ" 1>&2
       (diff -c obs-l5.O $srcdir/obs-l5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l5(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l5.O $srcdir/obs-l5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l5.E || rm -f obs-l5.E
_POSIX2_VERSION=199209 $xx +2l < $srcdir/obs-l5.I > obs-l5.O 2> obs-l5.E
code=$?
if test $code != 0; then
  $echo "Test obs-l5(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l5.O $srcdir/obs-l5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l5(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l5(_POSIX2_VERSION=199209:<) failed: files obs-l5.O and $srcdir/obs-l5.X differ" 1>&2
       (diff -c obs-l5.O $srcdir/obs-l5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l5(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l5.O $srcdir/obs-l5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l5.E || rm -f obs-l5.E
_POSIX2_VERSION=199209 $xx -1 $srcdir/obs-1.I > obs-1.O 2> obs-1.E
code=$?
if test $code != 0; then
  $echo "Test obs-1(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-1.O $srcdir/obs-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-1(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-1(_POSIX2_VERSION=199209:F) failed: files obs-1.O and $srcdir/obs-1.X differ" 1>&2
       (diff -c obs-1.O $srcdir/obs-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-1(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-1.O $srcdir/obs-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-1.E || rm -f obs-1.E
cat $srcdir/obs-1.I | _POSIX2_VERSION=199209 $xx -1 > obs-1.O 2> obs-1.E
code=$?
if test $code != 0; then
  $echo "Test obs-1(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-1.O $srcdir/obs-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-1(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-1(_POSIX2_VERSION=199209:|) failed: files obs-1.O and $srcdir/obs-1.X differ" 1>&2
       (diff -c obs-1.O $srcdir/obs-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-1(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-1.O $srcdir/obs-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-1.E || rm -f obs-1.E
_POSIX2_VERSION=199209 $xx -1 < $srcdir/obs-1.I > obs-1.O 2> obs-1.E
code=$?
if test $code != 0; then
  $echo "Test obs-1(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-1.O $srcdir/obs-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-1(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-1(_POSIX2_VERSION=199209:<) failed: files obs-1.O and $srcdir/obs-1.X differ" 1>&2
       (diff -c obs-1.O $srcdir/obs-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-1(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-1.O $srcdir/obs-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-1.E || rm -f obs-1.E
_POSIX2_VERSION=199209 $xx -1 $srcdir/obs-2.I > obs-2.O 2> obs-2.E
code=$?
if test $code != 0; then
  $echo "Test obs-2(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-2.O $srcdir/obs-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-2(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-2(_POSIX2_VERSION=199209:F) failed: files obs-2.O and $srcdir/obs-2.X differ" 1>&2
       (diff -c obs-2.O $srcdir/obs-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-2(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-2.O $srcdir/obs-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-2.E || rm -f obs-2.E
cat $srcdir/obs-2.I | _POSIX2_VERSION=199209 $xx -1 > obs-2.O 2> obs-2.E
code=$?
if test $code != 0; then
  $echo "Test obs-2(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-2.O $srcdir/obs-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-2(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-2(_POSIX2_VERSION=199209:|) failed: files obs-2.O and $srcdir/obs-2.X differ" 1>&2
       (diff -c obs-2.O $srcdir/obs-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-2(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-2.O $srcdir/obs-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-2.E || rm -f obs-2.E
_POSIX2_VERSION=199209 $xx -1 < $srcdir/obs-2.I > obs-2.O 2> obs-2.E
code=$?
if test $code != 0; then
  $echo "Test obs-2(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-2.O $srcdir/obs-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-2(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-2(_POSIX2_VERSION=199209:<) failed: files obs-2.O and $srcdir/obs-2.X differ" 1>&2
       (diff -c obs-2.O $srcdir/obs-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-2(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-2.O $srcdir/obs-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-2.E || rm -f obs-2.E
_POSIX2_VERSION=199209 $xx -1 $srcdir/obs-3.I > obs-3.O 2> obs-3.E
code=$?
if test $code != 0; then
  $echo "Test obs-3(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-3.O $srcdir/obs-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-3(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-3(_POSIX2_VERSION=199209:F) failed: files obs-3.O and $srcdir/obs-3.X differ" 1>&2
       (diff -c obs-3.O $srcdir/obs-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-3(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-3.O $srcdir/obs-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-3.E || rm -f obs-3.E
cat $srcdir/obs-3.I | _POSIX2_VERSION=199209 $xx -1 > obs-3.O 2> obs-3.E
code=$?
if test $code != 0; then
  $echo "Test obs-3(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-3.O $srcdir/obs-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-3(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-3(_POSIX2_VERSION=199209:|) failed: files obs-3.O and $srcdir/obs-3.X differ" 1>&2
       (diff -c obs-3.O $srcdir/obs-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-3(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-3.O $srcdir/obs-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-3.E || rm -f obs-3.E
_POSIX2_VERSION=199209 $xx -1 < $srcdir/obs-3.I > obs-3.O 2> obs-3.E
code=$?
if test $code != 0; then
  $echo "Test obs-3(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-3.O $srcdir/obs-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-3(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-3(_POSIX2_VERSION=199209:<) failed: files obs-3.O and $srcdir/obs-3.X differ" 1>&2
       (diff -c obs-3.O $srcdir/obs-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-3(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-3.O $srcdir/obs-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-3.E || rm -f obs-3.E
_POSIX2_VERSION=199209 $xx +1 $srcdir/obs-4.I > obs-4.O 2> obs-4.E
code=$?
if test $code != 0; then
  $echo "Test obs-4(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-4.O $srcdir/obs-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-4(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-4(_POSIX2_VERSION=199209:F) failed: files obs-4.O and $srcdir/obs-4.X differ" 1>&2
       (diff -c obs-4.O $srcdir/obs-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-4(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-4.O $srcdir/obs-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-4.E || rm -f obs-4.E
cat $srcdir/obs-4.I | _POSIX2_VERSION=199209 $xx +1 > obs-4.O 2> obs-4.E
code=$?
if test $code != 0; then
  $echo "Test obs-4(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-4.O $srcdir/obs-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-4(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-4(_POSIX2_VERSION=199209:|) failed: files obs-4.O and $srcdir/obs-4.X differ" 1>&2
       (diff -c obs-4.O $srcdir/obs-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-4(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-4.O $srcdir/obs-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-4.E || rm -f obs-4.E
_POSIX2_VERSION=199209 $xx +1 < $srcdir/obs-4.I > obs-4.O 2> obs-4.E
code=$?
if test $code != 0; then
  $echo "Test obs-4(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-4.O $srcdir/obs-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-4(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-4(_POSIX2_VERSION=199209:<) failed: files obs-4.O and $srcdir/obs-4.X differ" 1>&2
       (diff -c obs-4.O $srcdir/obs-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-4(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-4.O $srcdir/obs-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-4.E || rm -f obs-4.E
_POSIX2_VERSION=199209 $xx +2 $srcdir/obs-5.I > obs-5.O 2> obs-5.E
code=$?
if test $code != 0; then
  $echo "Test obs-5(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-5.O $srcdir/obs-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-5(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-5(_POSIX2_VERSION=199209:F) failed: files obs-5.O and $srcdir/obs-5.X differ" 1>&2
       (diff -c obs-5.O $srcdir/obs-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-5(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-5.O $srcdir/obs-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-5.E || rm -f obs-5.E
cat $srcdir/obs-5.I | _POSIX2_VERSION=199209 $xx +2 > obs-5.O 2> obs-5.E
code=$?
if test $code != 0; then
  $echo "Test obs-5(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-5.O $srcdir/obs-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-5(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-5(_POSIX2_VERSION=199209:|) failed: files obs-5.O and $srcdir/obs-5.X differ" 1>&2
       (diff -c obs-5.O $srcdir/obs-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-5(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-5.O $srcdir/obs-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-5.E || rm -f obs-5.E
_POSIX2_VERSION=199209 $xx +2 < $srcdir/obs-5.I > obs-5.O 2> obs-5.E
code=$?
if test $code != 0; then
  $echo "Test obs-5(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-5.O $srcdir/obs-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-5(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-5(_POSIX2_VERSION=199209:<) failed: files obs-5.O and $srcdir/obs-5.X differ" 1>&2
       (diff -c obs-5.O $srcdir/obs-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-5(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-5.O $srcdir/obs-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-5.E || rm -f obs-5.E
_POSIX2_VERSION=199209 $xx +c $srcdir/obsx-1.I > obsx-1.O 2> obsx-1.E
code=$?
if test $code != 0; then
  $echo "Test obsx-1(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-1.O $srcdir/obsx-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-1(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obsx-1(_POSIX2_VERSION=199209:F) failed: files obsx-1.O and $srcdir/obsx-1.X differ" 1>&2
       (diff -c obsx-1.O $srcdir/obsx-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-1(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obsx-1.O $srcdir/obsx-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-1.E || rm -f obsx-1.E
cat $srcdir/obsx-1.I | _POSIX2_VERSION=199209 $xx +c > obsx-1.O 2> obsx-1.E
code=$?
if test $code != 0; then
  $echo "Test obsx-1(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-1.O $srcdir/obsx-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-1(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obsx-1(_POSIX2_VERSION=199209:|) failed: files obsx-1.O and $srcdir/obsx-1.X differ" 1>&2
       (diff -c obsx-1.O $srcdir/obsx-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-1(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obsx-1.O $srcdir/obsx-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-1.E || rm -f obsx-1.E
_POSIX2_VERSION=199209 $xx +c < $srcdir/obsx-1.I > obsx-1.O 2> obsx-1.E
code=$?
if test $code != 0; then
  $echo "Test obsx-1(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-1.O $srcdir/obsx-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-1(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obsx-1(_POSIX2_VERSION=199209:<) failed: files obsx-1.O and $srcdir/obsx-1.X differ" 1>&2
       (diff -c obsx-1.O $srcdir/obsx-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-1(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obsx-1.O $srcdir/obsx-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-1.E || rm -f obsx-1.E
_POSIX2_VERSION=199209 $xx +l $srcdir/obsx-2.I > obsx-2.O 2> obsx-2.E
code=$?
if test $code != 0; then
  $echo "Test obsx-2(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-2.O $srcdir/obsx-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-2(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obsx-2(_POSIX2_VERSION=199209:F) failed: files obsx-2.O and $srcdir/obsx-2.X differ" 1>&2
       (diff -c obsx-2.O $srcdir/obsx-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-2(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obsx-2.O $srcdir/obsx-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-2.E || rm -f obsx-2.E
cat $srcdir/obsx-2.I | _POSIX2_VERSION=199209 $xx +l > obsx-2.O 2> obsx-2.E
code=$?
if test $code != 0; then
  $echo "Test obsx-2(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-2.O $srcdir/obsx-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-2(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obsx-2(_POSIX2_VERSION=199209:|) failed: files obsx-2.O and $srcdir/obsx-2.X differ" 1>&2
       (diff -c obsx-2.O $srcdir/obsx-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-2(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obsx-2.O $srcdir/obsx-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-2.E || rm -f obsx-2.E
_POSIX2_VERSION=199209 $xx +l < $srcdir/obsx-2.I > obsx-2.O 2> obsx-2.E
code=$?
if test $code != 0; then
  $echo "Test obsx-2(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obsx-2.O $srcdir/obsx-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obsx-2(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obsx-2(_POSIX2_VERSION=199209:<) failed: files obsx-2.O and $srcdir/obsx-2.X differ" 1>&2
       (diff -c obsx-2.O $srcdir/obsx-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obsx-2(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obsx-2.O $srcdir/obsx-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obsx-2.E || rm -f obsx-2.E
_POSIX2_VERSION=199209 $xx -l $srcdir/obs-l.I > obs-l.O 2> obs-l.E
code=$?
if test $code != 0; then
  $echo "Test obs-l(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l.O $srcdir/obs-l.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test obs-l(_POSIX2_VERSION=199209:F) failed: files obs-l.O and $srcdir/obs-l.X differ" 1>&2
       (diff -c obs-l.O $srcdir/obs-l.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp obs-l.O $srcdir/obs-l.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l.E || rm -f obs-l.E
cat $srcdir/obs-l.I | _POSIX2_VERSION=199209 $xx -l > obs-l.O 2> obs-l.E
code=$?
if test $code != 0; then
  $echo "Test obs-l(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l.O $srcdir/obs-l.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test obs-l(_POSIX2_VERSION=199209:|) failed: files obs-l.O and $srcdir/obs-l.X differ" 1>&2
       (diff -c obs-l.O $srcdir/obs-l.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp obs-l.O $srcdir/obs-l.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l.E || rm -f obs-l.E
_POSIX2_VERSION=199209 $xx -l < $srcdir/obs-l.I > obs-l.O 2> obs-l.E
code=$?
if test $code != 0; then
  $echo "Test obs-l(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp obs-l.O $srcdir/obs-l.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed obs-l(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test obs-l(_POSIX2_VERSION=199209:<) failed: files obs-l.O and $srcdir/obs-l.X differ" 1>&2
       (diff -c obs-l.O $srcdir/obs-l.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test obs-l(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp obs-l.O $srcdir/obs-l.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s obs-l.E || rm -f obs-l.E
_POSIX2_VERSION=199209 $xx +cl $srcdir/err-1.I > err-1.O 2> err-1.E
code=$?
if test $code != 1; then
  $echo "Test err-1(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-1.O $srcdir/err-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-1(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test err-1(_POSIX2_VERSION=199209:F) failed: files err-1.O and $srcdir/err-1.X differ" 1>&2
       (diff -c err-1.O $srcdir/err-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-1(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp err-1.O $srcdir/err-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-1.E || rm -f err-1.E
cat $srcdir/err-1.I | _POSIX2_VERSION=199209 $xx +cl > err-1.O 2> err-1.E
code=$?
if test $code != 1; then
  $echo "Test err-1(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-1.O $srcdir/err-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-1(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test err-1(_POSIX2_VERSION=199209:|) failed: files err-1.O and $srcdir/err-1.X differ" 1>&2
       (diff -c err-1.O $srcdir/err-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-1(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp err-1.O $srcdir/err-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-1.E || rm -f err-1.E
_POSIX2_VERSION=199209 $xx +cl < $srcdir/err-1.I > err-1.O 2> err-1.E
code=$?
if test $code != 1; then
  $echo "Test err-1(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-1.O $srcdir/err-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-1(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test err-1(_POSIX2_VERSION=199209:<) failed: files err-1.O and $srcdir/err-1.X differ" 1>&2
       (diff -c err-1.O $srcdir/err-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-1(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp err-1.O $srcdir/err-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-1.E || rm -f err-1.E
$xx -cl $srcdir/err-2.I > err-2.O 2> err-2.E
code=$?
if test $code != 1; then
  $echo "Test err-2(F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-2.O $srcdir/err-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-2(F)"; fi;;
    1) $echo "Test err-2(F) failed: files err-2.O and $srcdir/err-2.X differ" 1>&2
       (diff -c err-2.O $srcdir/err-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-2(F) may have failed." 1>&2
       $echo The command "cmp err-2.O $srcdir/err-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-2.E || rm -f err-2.E
cat $srcdir/err-2.I | $xx -cl > err-2.O 2> err-2.E
code=$?
if test $code != 1; then
  $echo "Test err-2(|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-2.O $srcdir/err-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-2(|)"; fi;;
    1) $echo "Test err-2(|) failed: files err-2.O and $srcdir/err-2.X differ" 1>&2
       (diff -c err-2.O $srcdir/err-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-2(|) may have failed." 1>&2
       $echo The command "cmp err-2.O $srcdir/err-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-2.E || rm -f err-2.E
$xx -cl < $srcdir/err-2.I > err-2.O 2> err-2.E
code=$?
if test $code != 1; then
  $echo "Test err-2(<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-2.O $srcdir/err-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-2(<)"; fi;;
    1) $echo "Test err-2(<) failed: files err-2.O and $srcdir/err-2.X differ" 1>&2
       (diff -c err-2.O $srcdir/err-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-2(<) may have failed." 1>&2
       $echo The command "cmp err-2.O $srcdir/err-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-2.E || rm -f err-2.E
_POSIX2_VERSION=199209 $xx +2cz $srcdir/err-3.I > err-3.O 2> err-3.E
code=$?
if test $code != 1; then
  $echo "Test err-3(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-3.O $srcdir/err-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-3(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test err-3(_POSIX2_VERSION=199209:F) failed: files err-3.O and $srcdir/err-3.X differ" 1>&2
       (diff -c err-3.O $srcdir/err-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-3(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp err-3.O $srcdir/err-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-3.E || rm -f err-3.E
cat $srcdir/err-3.I | _POSIX2_VERSION=199209 $xx +2cz > err-3.O 2> err-3.E
code=$?
if test $code != 1; then
  $echo "Test err-3(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-3.O $srcdir/err-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-3(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test err-3(_POSIX2_VERSION=199209:|) failed: files err-3.O and $srcdir/err-3.X differ" 1>&2
       (diff -c err-3.O $srcdir/err-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-3(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp err-3.O $srcdir/err-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-3.E || rm -f err-3.E
_POSIX2_VERSION=199209 $xx +2cz < $srcdir/err-3.I > err-3.O 2> err-3.E
code=$?
if test $code != 1; then
  $echo "Test err-3(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-3.O $srcdir/err-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-3(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test err-3(_POSIX2_VERSION=199209:<) failed: files err-3.O and $srcdir/err-3.X differ" 1>&2
       (diff -c err-3.O $srcdir/err-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-3(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp err-3.O $srcdir/err-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-3.E || rm -f err-3.E
_POSIX2_VERSION=199209 $xx -2cX $srcdir/err-4.I > err-4.O 2> err-4.E
code=$?
if test $code != 1; then
  $echo "Test err-4(_POSIX2_VERSION=199209:F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-4.O $srcdir/err-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-4(_POSIX2_VERSION=199209:F)"; fi;;
    1) $echo "Test err-4(_POSIX2_VERSION=199209:F) failed: files err-4.O and $srcdir/err-4.X differ" 1>&2
       (diff -c err-4.O $srcdir/err-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-4(_POSIX2_VERSION=199209:F) may have failed." 1>&2
       $echo The command "cmp err-4.O $srcdir/err-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-4.E || rm -f err-4.E
cat $srcdir/err-4.I | _POSIX2_VERSION=199209 $xx -2cX > err-4.O 2> err-4.E
code=$?
if test $code != 1; then
  $echo "Test err-4(_POSIX2_VERSION=199209:|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-4.O $srcdir/err-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-4(_POSIX2_VERSION=199209:|)"; fi;;
    1) $echo "Test err-4(_POSIX2_VERSION=199209:|) failed: files err-4.O and $srcdir/err-4.X differ" 1>&2
       (diff -c err-4.O $srcdir/err-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-4(_POSIX2_VERSION=199209:|) may have failed." 1>&2
       $echo The command "cmp err-4.O $srcdir/err-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-4.E || rm -f err-4.E
_POSIX2_VERSION=199209 $xx -2cX < $srcdir/err-4.I > err-4.O 2> err-4.E
code=$?
if test $code != 1; then
  $echo "Test err-4(_POSIX2_VERSION=199209:<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-4.O $srcdir/err-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-4(_POSIX2_VERSION=199209:<)"; fi;;
    1) $echo "Test err-4(_POSIX2_VERSION=199209:<) failed: files err-4.O and $srcdir/err-4.X differ" 1>&2
       (diff -c err-4.O $srcdir/err-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-4(_POSIX2_VERSION=199209:<) may have failed." 1>&2
       $echo The command "cmp err-4.O $srcdir/err-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-4.E || rm -f err-4.E
$xx -c99999999999999999999 $srcdir/err-5.I > err-5.O 2> err-5.E
code=$?
if test $code != 1; then
  $echo "Test err-5(F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-5.O $srcdir/err-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-5(F)"; fi;;
    1) $echo "Test err-5(F) failed: files err-5.O and $srcdir/err-5.X differ" 1>&2
       (diff -c err-5.O $srcdir/err-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-5(F) may have failed." 1>&2
       $echo The command "cmp err-5.O $srcdir/err-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-5.E || rm -f err-5.E
cat $srcdir/err-5.I | $xx -c99999999999999999999 > err-5.O 2> err-5.E
code=$?
if test $code != 1; then
  $echo "Test err-5(|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-5.O $srcdir/err-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-5(|)"; fi;;
    1) $echo "Test err-5(|) failed: files err-5.O and $srcdir/err-5.X differ" 1>&2
       (diff -c err-5.O $srcdir/err-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-5(|) may have failed." 1>&2
       $echo The command "cmp err-5.O $srcdir/err-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-5.E || rm -f err-5.E
$xx -c99999999999999999999 < $srcdir/err-5.I > err-5.O 2> err-5.E
code=$?
if test $code != 1; then
  $echo "Test err-5(<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-5.O $srcdir/err-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-5(<)"; fi;;
    1) $echo "Test err-5(<) failed: files err-5.O and $srcdir/err-5.X differ" 1>&2
       (diff -c err-5.O $srcdir/err-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-5(<) may have failed." 1>&2
       $echo The command "cmp err-5.O $srcdir/err-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-5.E || rm -f err-5.E
$xx -c $srcdir/err-6.I > err-6.O 2> err-6.E
code=$?
if test $code != 1; then
  $echo "Test err-6(F) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-6.O $srcdir/err-6.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-6(F)"; fi;;
    1) $echo "Test err-6(F) failed: files err-6.O and $srcdir/err-6.X differ" 1>&2
       (diff -c err-6.O $srcdir/err-6.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-6(F) may have failed." 1>&2
       $echo The command "cmp err-6.O $srcdir/err-6.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-6.E || rm -f err-6.E
cat $srcdir/err-6.I | $xx -c > err-6.O 2> err-6.E
code=$?
if test $code != 1; then
  $echo "Test err-6(|) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-6.O $srcdir/err-6.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-6(|)"; fi;;
    1) $echo "Test err-6(|) failed: files err-6.O and $srcdir/err-6.X differ" 1>&2
       (diff -c err-6.O $srcdir/err-6.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-6(|) may have failed." 1>&2
       $echo The command "cmp err-6.O $srcdir/err-6.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-6.E || rm -f err-6.E
$xx -c < $srcdir/err-6.I > err-6.O 2> err-6.E
code=$?
if test $code != 1; then
  $echo "Test err-6(<) failed: ../../src/tail return code $code differs from expected value 1" 1>&2
  errors=`expr $errors + 1`
else
  cmp err-6.O $srcdir/err-6.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed err-6(<)"; fi;;
    1) $echo "Test err-6(<) failed: files err-6.O and $srcdir/err-6.X differ" 1>&2
       (diff -c err-6.O $srcdir/err-6.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test err-6(<) may have failed." 1>&2
       $echo The command "cmp err-6.O $srcdir/err-6.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s err-6.E || rm -f err-6.E
cat $srcdir/minus-1.I | $xx - > minus-1.O 2> minus-1.E
code=$?
if test $code != 0; then
  $echo "Test minus-1(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp minus-1.O $srcdir/minus-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed minus-1(|)"; fi;;
    1) $echo "Test minus-1(|) failed: files minus-1.O and $srcdir/minus-1.X differ" 1>&2
       (diff -c minus-1.O $srcdir/minus-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test minus-1(|) may have failed." 1>&2
       $echo The command "cmp minus-1.O $srcdir/minus-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s minus-1.E || rm -f minus-1.E
$xx - < $srcdir/minus-1.I > minus-1.O 2> minus-1.E
code=$?
if test $code != 0; then
  $echo "Test minus-1(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp minus-1.O $srcdir/minus-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed minus-1(<)"; fi;;
    1) $echo "Test minus-1(<) failed: files minus-1.O and $srcdir/minus-1.X differ" 1>&2
       (diff -c minus-1.O $srcdir/minus-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test minus-1(<) may have failed." 1>&2
       $echo The command "cmp minus-1.O $srcdir/minus-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s minus-1.E || rm -f minus-1.E
cat $srcdir/minus-2.I | $xx - > minus-2.O 2> minus-2.E
code=$?
if test $code != 0; then
  $echo "Test minus-2(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp minus-2.O $srcdir/minus-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed minus-2(|)"; fi;;
    1) $echo "Test minus-2(|) failed: files minus-2.O and $srcdir/minus-2.X differ" 1>&2
       (diff -c minus-2.O $srcdir/minus-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test minus-2(|) may have failed." 1>&2
       $echo The command "cmp minus-2.O $srcdir/minus-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s minus-2.E || rm -f minus-2.E
$xx - < $srcdir/minus-2.I > minus-2.O 2> minus-2.E
code=$?
if test $code != 0; then
  $echo "Test minus-2(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp minus-2.O $srcdir/minus-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed minus-2(<)"; fi;;
    1) $echo "Test minus-2(<) failed: files minus-2.O and $srcdir/minus-2.X differ" 1>&2
       (diff -c minus-2.O $srcdir/minus-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test minus-2(<) may have failed." 1>&2
       $echo The command "cmp minus-2.O $srcdir/minus-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s minus-2.E || rm -f minus-2.E
$xx -n 10 $srcdir/n-1.I > n-1.O 2> n-1.E
code=$?
if test $code != 0; then
  $echo "Test n-1(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-1.O $srcdir/n-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-1(F)"; fi;;
    1) $echo "Test n-1(F) failed: files n-1.O and $srcdir/n-1.X differ" 1>&2
       (diff -c n-1.O $srcdir/n-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-1(F) may have failed." 1>&2
       $echo The command "cmp n-1.O $srcdir/n-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-1.E || rm -f n-1.E
cat $srcdir/n-1.I | $xx -n 10 > n-1.O 2> n-1.E
code=$?
if test $code != 0; then
  $echo "Test n-1(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-1.O $srcdir/n-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-1(|)"; fi;;
    1) $echo "Test n-1(|) failed: files n-1.O and $srcdir/n-1.X differ" 1>&2
       (diff -c n-1.O $srcdir/n-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-1(|) may have failed." 1>&2
       $echo The command "cmp n-1.O $srcdir/n-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-1.E || rm -f n-1.E
$xx -n 10 < $srcdir/n-1.I > n-1.O 2> n-1.E
code=$?
if test $code != 0; then
  $echo "Test n-1(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-1.O $srcdir/n-1.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-1(<)"; fi;;
    1) $echo "Test n-1(<) failed: files n-1.O and $srcdir/n-1.X differ" 1>&2
       (diff -c n-1.O $srcdir/n-1.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-1(<) may have failed." 1>&2
       $echo The command "cmp n-1.O $srcdir/n-1.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-1.E || rm -f n-1.E
$xx -n -10 $srcdir/n-2.I > n-2.O 2> n-2.E
code=$?
if test $code != 0; then
  $echo "Test n-2(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-2.O $srcdir/n-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-2(F)"; fi;;
    1) $echo "Test n-2(F) failed: files n-2.O and $srcdir/n-2.X differ" 1>&2
       (diff -c n-2.O $srcdir/n-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-2(F) may have failed." 1>&2
       $echo The command "cmp n-2.O $srcdir/n-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-2.E || rm -f n-2.E
cat $srcdir/n-2.I | $xx -n -10 > n-2.O 2> n-2.E
code=$?
if test $code != 0; then
  $echo "Test n-2(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-2.O $srcdir/n-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-2(|)"; fi;;
    1) $echo "Test n-2(|) failed: files n-2.O and $srcdir/n-2.X differ" 1>&2
       (diff -c n-2.O $srcdir/n-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-2(|) may have failed." 1>&2
       $echo The command "cmp n-2.O $srcdir/n-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-2.E || rm -f n-2.E
$xx -n -10 < $srcdir/n-2.I > n-2.O 2> n-2.E
code=$?
if test $code != 0; then
  $echo "Test n-2(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-2.O $srcdir/n-2.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-2(<)"; fi;;
    1) $echo "Test n-2(<) failed: files n-2.O and $srcdir/n-2.X differ" 1>&2
       (diff -c n-2.O $srcdir/n-2.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-2(<) may have failed." 1>&2
       $echo The command "cmp n-2.O $srcdir/n-2.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-2.E || rm -f n-2.E
$xx -n +10 $srcdir/n-3.I > n-3.O 2> n-3.E
code=$?
if test $code != 0; then
  $echo "Test n-3(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-3.O $srcdir/n-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-3(F)"; fi;;
    1) $echo "Test n-3(F) failed: files n-3.O and $srcdir/n-3.X differ" 1>&2
       (diff -c n-3.O $srcdir/n-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-3(F) may have failed." 1>&2
       $echo The command "cmp n-3.O $srcdir/n-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-3.E || rm -f n-3.E
cat $srcdir/n-3.I | $xx -n +10 > n-3.O 2> n-3.E
code=$?
if test $code != 0; then
  $echo "Test n-3(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-3.O $srcdir/n-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-3(|)"; fi;;
    1) $echo "Test n-3(|) failed: files n-3.O and $srcdir/n-3.X differ" 1>&2
       (diff -c n-3.O $srcdir/n-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-3(|) may have failed." 1>&2
       $echo The command "cmp n-3.O $srcdir/n-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-3.E || rm -f n-3.E
$xx -n +10 < $srcdir/n-3.I > n-3.O 2> n-3.E
code=$?
if test $code != 0; then
  $echo "Test n-3(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-3.O $srcdir/n-3.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-3(<)"; fi;;
    1) $echo "Test n-3(<) failed: files n-3.O and $srcdir/n-3.X differ" 1>&2
       (diff -c n-3.O $srcdir/n-3.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-3(<) may have failed." 1>&2
       $echo The command "cmp n-3.O $srcdir/n-3.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-3.E || rm -f n-3.E
$xx -n +0 $srcdir/n-4.I > n-4.O 2> n-4.E
code=$?
if test $code != 0; then
  $echo "Test n-4(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4.O $srcdir/n-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4(F)"; fi;;
    1) $echo "Test n-4(F) failed: files n-4.O and $srcdir/n-4.X differ" 1>&2
       (diff -c n-4.O $srcdir/n-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4(F) may have failed." 1>&2
       $echo The command "cmp n-4.O $srcdir/n-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4.E || rm -f n-4.E
cat $srcdir/n-4.I | $xx -n +0 > n-4.O 2> n-4.E
code=$?
if test $code != 0; then
  $echo "Test n-4(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4.O $srcdir/n-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4(|)"; fi;;
    1) $echo "Test n-4(|) failed: files n-4.O and $srcdir/n-4.X differ" 1>&2
       (diff -c n-4.O $srcdir/n-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4(|) may have failed." 1>&2
       $echo The command "cmp n-4.O $srcdir/n-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4.E || rm -f n-4.E
$xx -n +0 < $srcdir/n-4.I > n-4.O 2> n-4.E
code=$?
if test $code != 0; then
  $echo "Test n-4(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4.O $srcdir/n-4.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4(<)"; fi;;
    1) $echo "Test n-4(<) failed: files n-4.O and $srcdir/n-4.X differ" 1>&2
       (diff -c n-4.O $srcdir/n-4.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4(<) may have failed." 1>&2
       $echo The command "cmp n-4.O $srcdir/n-4.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4.E || rm -f n-4.E
$xx -n +1 $srcdir/n-4a.I > n-4a.O 2> n-4a.E
code=$?
if test $code != 0; then
  $echo "Test n-4a(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4a.O $srcdir/n-4a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4a(F)"; fi;;
    1) $echo "Test n-4a(F) failed: files n-4a.O and $srcdir/n-4a.X differ" 1>&2
       (diff -c n-4a.O $srcdir/n-4a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4a(F) may have failed." 1>&2
       $echo The command "cmp n-4a.O $srcdir/n-4a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4a.E || rm -f n-4a.E
cat $srcdir/n-4a.I | $xx -n +1 > n-4a.O 2> n-4a.E
code=$?
if test $code != 0; then
  $echo "Test n-4a(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4a.O $srcdir/n-4a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4a(|)"; fi;;
    1) $echo "Test n-4a(|) failed: files n-4a.O and $srcdir/n-4a.X differ" 1>&2
       (diff -c n-4a.O $srcdir/n-4a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4a(|) may have failed." 1>&2
       $echo The command "cmp n-4a.O $srcdir/n-4a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4a.E || rm -f n-4a.E
$xx -n +1 < $srcdir/n-4a.I > n-4a.O 2> n-4a.E
code=$?
if test $code != 0; then
  $echo "Test n-4a(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-4a.O $srcdir/n-4a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-4a(<)"; fi;;
    1) $echo "Test n-4a(<) failed: files n-4a.O and $srcdir/n-4a.X differ" 1>&2
       (diff -c n-4a.O $srcdir/n-4a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-4a(<) may have failed." 1>&2
       $echo The command "cmp n-4a.O $srcdir/n-4a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-4a.E || rm -f n-4a.E
$xx -n -0 $srcdir/n-5.I > n-5.O 2> n-5.E
code=$?
if test $code != 0; then
  $echo "Test n-5(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5.O $srcdir/n-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5(F)"; fi;;
    1) $echo "Test n-5(F) failed: files n-5.O and $srcdir/n-5.X differ" 1>&2
       (diff -c n-5.O $srcdir/n-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5(F) may have failed." 1>&2
       $echo The command "cmp n-5.O $srcdir/n-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5.E || rm -f n-5.E
cat $srcdir/n-5.I | $xx -n -0 > n-5.O 2> n-5.E
code=$?
if test $code != 0; then
  $echo "Test n-5(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5.O $srcdir/n-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5(|)"; fi;;
    1) $echo "Test n-5(|) failed: files n-5.O and $srcdir/n-5.X differ" 1>&2
       (diff -c n-5.O $srcdir/n-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5(|) may have failed." 1>&2
       $echo The command "cmp n-5.O $srcdir/n-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5.E || rm -f n-5.E
$xx -n -0 < $srcdir/n-5.I > n-5.O 2> n-5.E
code=$?
if test $code != 0; then
  $echo "Test n-5(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5.O $srcdir/n-5.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5(<)"; fi;;
    1) $echo "Test n-5(<) failed: files n-5.O and $srcdir/n-5.X differ" 1>&2
       (diff -c n-5.O $srcdir/n-5.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5(<) may have failed." 1>&2
       $echo The command "cmp n-5.O $srcdir/n-5.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5.E || rm -f n-5.E
$xx -n -1 $srcdir/n-5a.I > n-5a.O 2> n-5a.E
code=$?
if test $code != 0; then
  $echo "Test n-5a(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5a.O $srcdir/n-5a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5a(F)"; fi;;
    1) $echo "Test n-5a(F) failed: files n-5a.O and $srcdir/n-5a.X differ" 1>&2
       (diff -c n-5a.O $srcdir/n-5a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5a(F) may have failed." 1>&2
       $echo The command "cmp n-5a.O $srcdir/n-5a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5a.E || rm -f n-5a.E
cat $srcdir/n-5a.I | $xx -n -1 > n-5a.O 2> n-5a.E
code=$?
if test $code != 0; then
  $echo "Test n-5a(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5a.O $srcdir/n-5a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5a(|)"; fi;;
    1) $echo "Test n-5a(|) failed: files n-5a.O and $srcdir/n-5a.X differ" 1>&2
       (diff -c n-5a.O $srcdir/n-5a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5a(|) may have failed." 1>&2
       $echo The command "cmp n-5a.O $srcdir/n-5a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5a.E || rm -f n-5a.E
$xx -n -1 < $srcdir/n-5a.I > n-5a.O 2> n-5a.E
code=$?
if test $code != 0; then
  $echo "Test n-5a(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5a.O $srcdir/n-5a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5a(<)"; fi;;
    1) $echo "Test n-5a(<) failed: files n-5a.O and $srcdir/n-5a.X differ" 1>&2
       (diff -c n-5a.O $srcdir/n-5a.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5a(<) may have failed." 1>&2
       $echo The command "cmp n-5a.O $srcdir/n-5a.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5a.E || rm -f n-5a.E
$xx -n  0 $srcdir/n-5b.I > n-5b.O 2> n-5b.E
code=$?
if test $code != 0; then
  $echo "Test n-5b(F) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5b.O $srcdir/n-5b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5b(F)"; fi;;
    1) $echo "Test n-5b(F) failed: files n-5b.O and $srcdir/n-5b.X differ" 1>&2
       (diff -c n-5b.O $srcdir/n-5b.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5b(F) may have failed." 1>&2
       $echo The command "cmp n-5b.O $srcdir/n-5b.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5b.E || rm -f n-5b.E
cat $srcdir/n-5b.I | $xx -n  0 > n-5b.O 2> n-5b.E
code=$?
if test $code != 0; then
  $echo "Test n-5b(|) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5b.O $srcdir/n-5b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5b(|)"; fi;;
    1) $echo "Test n-5b(|) failed: files n-5b.O and $srcdir/n-5b.X differ" 1>&2
       (diff -c n-5b.O $srcdir/n-5b.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5b(|) may have failed." 1>&2
       $echo The command "cmp n-5b.O $srcdir/n-5b.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5b.E || rm -f n-5b.E
$xx -n  0 < $srcdir/n-5b.I > n-5b.O 2> n-5b.E
code=$?
if test $code != 0; then
  $echo "Test n-5b(<) failed: ../../src/tail return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp n-5b.O $srcdir/n-5b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE"; then $echo "passed n-5b(<)"; fi;;
    1) $echo "Test n-5b(<) failed: files n-5b.O and $srcdir/n-5b.X differ" 1>&2
       (diff -c n-5b.O $srcdir/n-5b.X) 2> /dev/null
       errors=`expr $errors + 1`;;
    2) $echo "Test n-5b(<) may have failed." 1>&2
       $echo The command "cmp n-5b.O $srcdir/n-5b.X" failed. 1>&2
       errors=`expr $errors + 1`;;
  esac
fi
test -s n-5b.E || rm -f n-5b.E
if test $errors = 0; then
  $echo Passed all 100 tests. 1>&2
else
  $echo Failed $errors tests. 1>&2
fi
test $errors = 0 || errors=1
exit $errors
