#!/bin/sh
# move files/directories across file system boundaries
# and make sure acls are preserved

. $srcdir/../acl
. $srcdir/setup
# Make sure we get English translations.
. $srcdir/../lang-default

if test "$VERBOSE" = yes; then
  set -x
  mv --version
  getfacl --version
  setfacl --version
fi

if test -z "$other_partition_tmpdir"; then
  (exit 77); exit 77
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

t0="$t0 $other_partition_tmpdir"

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

# move the access acl of a file
touch file || framework_failure=1
setfacl -m user:bin:rw file || framework_failure=1
acl1=`getfacl file` || framework_failure=1
mv file $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl file` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

# move the access acl of a directory
mkdir dir || framework_failure=1
setfacl -m user:bin:rw dir || framework_failure=1
acl1=`getfacl dir` || framework_failure=1
mv dir $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl dir` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

# move the default acl of a directory
mkdir dir2 || framework_failure=1
setfacl -d -m user:bin:rw dir2 || framework_failure=1
acl1=`getfacl dir2` || framework_failure=1
mv dir2 $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl dir2` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

exit $fail
