#!/bin/sh
# move files/directories across file system boundaries
# and make sure acls are preserved

# Copyright (C) 2005, 2006 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

. $srcdir/../acl
. $srcdir/../other-fs-tmpdir
# Make sure we get English translations.
. $srcdir/../lang-default

# Skip this test if cp was built without ACL support:
grep '^#define USE_ACL 0' $CONFIG_HEADER > /dev/null && \
  {
    echo 1>&2 "$0: insufficient ACL support, so skipping this test"
    (exit 77); exit 77
  }

if test "$VERBOSE" = yes; then
  set -x
  mv --version
  getfacl --version
  setfacl --version
fi

if test -z "$other_partition_tmpdir"; then
  (exit 77); exit 77
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

t0="$t0 $other_partition_tmpdir"

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

touch file || framework_failure=1
t1=$other_partition_tmpdir/t1
touch $t1 || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

skip=no
# Ensure that setfacl and getfacl work on this file system.
setfacl -m user:bin:rw file 2> /dev/null || skip=.
# And on the destination file system.
setfacl -m user:bin:rw $t1 || skip=$other_partition_tmpdir
acl1=`getfacl file` || skip=yes

test $skip != no &&
  {
    echo "$0: '$skip' is not on a suitable file system for this test" 1>&2
    echo "$0: skipping this test" 1>&2
    (exit 77); exit 77
  }

# move the access acl of a file
mv file $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl file` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

# move the access acl of a directory
mkdir dir || framework_failure=1
setfacl -m user:bin:rw dir || framework_failure=1
acl1=`getfacl dir` || framework_failure=1
mv dir $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl dir` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

# move the default acl of a directory
mkdir dir2 || framework_failure=1
setfacl -d -m user:bin:rw dir2 || framework_failure=1
acl1=`getfacl dir2` || framework_failure=1
mv dir2 $other_partition_tmpdir || fail=1
acl2=`cd $other_partition_tmpdir && getfacl dir2` || framework_failure=1
test "$acl1" = "$acl2" || fail=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

exit $fail
