#!/bin/sh
# Force mv to use the copying code.

: ${MV=mv}
: ${RM=rm}

if test "$VERBOSE" = yes; then
  set -x
  $MV --version
fi

. $srcdir/setup

if test -z "$other_partition_tmpdir"; then
  exit 77
fi

a="$other_partition_tmpdir/a"
a2="$other_partition_tmpdir/a~"

framework_failure=0
$RM -f $a $a2 || framework_failure=1
: > $a || framework_failure=1
echo a > $a2 || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

# Make sure we get English translations.
LANGUAGE=C
export LANGUAGE
LC_ALL=C
export LC_ALL
LANG=C
export LANG

# This mv command should exit nonzero.
$MV -b -V simple $a2 $a > out 2>&1 && fail=1

sed \
   -e "s,$MV:,XXX:," \
   -e "s,$a,YYY," \
   -e "s,$a2,ZZZ," \
  out > out2

cat > exp <<\EOF
XXX: backing up `YYY' would destroy source;  `ZZZ' not moved
EOF

diff -u out2 exp || fail=1

$RM -fr out out2 exp $a $a2 $other_partition_tmpdir

exit $fail
