#!/bin/sh
# Make sure that `mv file unwritable-file' prompts the user
# and that `mv -f file unwritable-file' doesn't.

# Copyright (C) 2001, 2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

. $srcdir/test-lib.sh
require_controlling_input_terminal_
skip_if_root_
trap '' TTIN # Ignore SIGTTIN

touch f g h i || framework_failure
chmod 0 g i || framework_failure

fail=0

ls /dev/stdin >/dev/null 2>&1 \
  || skip_test_ 'there is no /dev/stdin file'

test -r /dev/stdin 2>&1 \
  || skip_test_ '/dev/stdin is not readable'

mv f g < /dev/stdin > out 2>&1 & pid=$!
sleep 1
kill $pid

# Make sure out contains the prompt.
case "`cat out`" in
  "mv: try to overwrite \`g', overriding mode 0000"*) ;;
  *) fail=1 ;;
esac

mv -f h i > out 2>&1 || fail=1
test -f i || fail=1
test -f h && fail=1

# Make sure there was no prompt.
case "`cat out`" in
  '') ;;
  *) fail=1 ;;
esac

Exit $fail
