#!/bin/sh
# move a directory into itself, with a twist

# Copyright (C) 1998, 1999, 2000 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

dir1=is3-dir1
dir2=is3-dir2

framework_failure=0
rm -rf $dir1 $dir2 || framework_failure=1
mkdir $dir1 $dir2 || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

# Make sure we get English translations.
. $srcdir/../lang-default

# This mv command should exit nonzero.
mv $dir1 $dir2 $dir2 > out 2>&1 && fail=1

sed \
   -e "s,mv:,XXX:,g" \
   -e "s,$dir2,ZZZ,g" \
  out > out2

cat > exp <<\EOF
XXX: cannot move `ZZZ' to a subdirectory of itself, `ZZZ/ZZZ'
EOF

cmp out2 exp || fail=1

rm -fr out out2 exp $dir1 $dir2

exit $fail
