#! /bin/sh

: ${MV=mv}
: ${RM=rm}
: ${MKNOD=mknod}

. $srcdir/setup

if test -z $other_partition_tmpdir; then
  exit 77
fi

null=.mv-null

test_failure=0

$RM -f $null || test_failure=1
$MKNOD $null p || test_failure=1
if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0
$MV $null $other_partition_tmpdir || fail=1

$RM -rf $null $other_partition_tmpdir

exit $fail
