#! /bin/sh

: ${LS=ls}
: ${MV=mv}
: ${MKDIR=mkdir}
: ${MKNOD=mknod}
: ${RM=rm}
: ${TOUCH=touch}

. $srcdir/setup

if test -z "$other_partition_tmpdir"; then
  exit 77
fi

null=.mv-null
dir=.mv-dir

test_failure=0

$RM -f $null || test_failure=1
$MKNOD $null p || test_failure=1
$MKDIR -p $dir/a/b/c $dir/d/e/f || test_failure=1
$TOUCH $dir/a/b/c/file1 $dir/d/e/f/file2 || test_failure=1

if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0
$MV $null $dir $other_partition_tmpdir || fail=1
# Make sure the files are gone.
test -f $null && fail=1
test -d $dir && fail=1

# cd $other_partition_tmpdir
# $LS -l -A -R $other_partition_tmpdir

$RM -rf $null $dir $other_partition_tmpdir

exit $fail
