#!/bin/sh
# ensure that mv gives one diagnostic, not two, when failing
# due to lack of permissions

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default
PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir -p no-write/dir || framework_failure=1
chmod u-w no-write || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

mv no-write/dir . > out 2>&1 && fail=1
cat <<\EOF > exp
mv: cannot move `no-write/dir' to `./dir': Permission denied
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit
