#!/bin/sh
# Ensure that `mv --reply=no f1 f2' works.

# Copyright (C) 2005-2007 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

. $srcdir/../lang-default
. $srcdir/../test-lib.sh

touch a b || framework_failure

fail=0

mv --interactive --reply=no a b > out 2>&1 || fail=1

# Both files must remain.
test -f a || fail=1
test -f b || fail=1

cat <<EOF > exp_err
mv: the --reply option is deprecated; use -i or -f instead
EOF

compare out exp_err || fail=1

(exit $fail); exit $fail
