#!/bin/sh
# Ensure that `mv --reply=no f1 f2' works.

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
touch a b || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

mv --interactive --reply=no a b > out 2>&1 || fail=1

# Both files must remain.
test -f a || fail=1
test -f b || fail=1

cat <<EOF > exp_err
mv: the --reply option is deprecated; use -i or -f instead
EOF

cmp out exp_err || fail=1
test $fail = 1 && diff out exp_err 2> /dev/null

(exit $fail); exit $fail
