#!/bin/sh
# Make sure that the copying code used in an inter-partition
# move unlinks a destination symlink before opening it.

# Copyright (C) 1999, 2000, 2007-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  mv --version
fi

. $srcdir/test-lib.sh
cleanup_() { rm -rf "$other_partition_tmpdir"; }
. "$abs_srcdir/other-fs-tmpdir"

rem_file="$other_partition_tmpdir/file"
rem_symlink="$other_partition_tmpdir/symlink"
file=to-sym-$$

fail=0

rm -f $file || framework_failure
echo local > $file || framework_failure
echo remote > $rem_file || framework_failure
ln -s $rem_file $rem_symlink || framework_failure

# This mv command should succeed, unlinking the symlink
# before copying.
mv $file $rem_symlink || fail=1

# Make sure $file is gone.
test -f $file && fail=1

# Make sure $rem_file is unmodified.
test `cat $rem_file` = remote || fail=1

Exit $fail
