#!/p/bin/perl -w

$tr = '../tr +io 5';
$tr = './tr';
$tr = 'tr';
$test = 0;
$| = 1;

print ":\nerrors=0\n";
$expected = '';
$s1 = '';
$input = '';
$flags = '';
$s1 = '';

while (<>)
  {
    next if (/^\s*#/);

    $test++;
    chop;
    $prog = '($test_name, $input,$flags,$s1,$s2,$expected,$e_ret_code) = ' . $_ . ';';
    eval $prog;
    $in = "t$test_name.in"; 
    $exp_name = 't' . $test_name . '.exp'; 
    $out = "t$test_name.out"; 

    open(IN, ">$in") || die "Couldn't open $in for writing.\n";
    print IN $input;
    close(IN);
    open(EXP, ">$exp_name")
	|| die "Couldn't open $exp_name for writing.\n";
    print EXP $expected;
    close(EXP);
    $arg2 = ($s2 ? " '$s2'" : '');
    $cmd = "$tr $flags \'$s1\'$arg2 < $in > $out";
    print <<EOF ;
$cmd 2> /dev/null
code=\$?
if test \$code != $e_ret_code ; then
  echo Test $test_name failed: tr return code \$code differs from expected value $e_ret_code 1>&2
  errors=`expr \$errors + 1`
else
  cmp $out $exp_name
  case \$? in
    0) if test "\$verbose" ; then echo passed $test_name; fi ;; # equal files
    1) echo Test $test_name failed: files $out and $exp_name differ 1>&2;
       errors=`expr \$errors + 1` ;;
    2) echo Test $test_name may have failed. 1>&2;
       echo The command \"cmp $out $exp_name\" failed. 1>&2 ;
       errors=`expr \$errors + 1` ;;
  esac
fi
EOF
  }
print <<EOF2 ;
if test \$errors = 0 ; then
  echo Passed all tests. 1>&2
else
  echo Failed \$errors tests. 1>&2
fi
EOF2
