#!/bin/sh
# Make sure touch can operate on a directory.
# This was broken in the 4.0[efg] test releases.

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

. $srcdir/test-lib.sh

fail=0
touch . || fail=1
Exit $fail
