#!/bin/sh
# make sure touch gives reasonable diagnostics

# Copyright (C) 2001-2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

. $srcdir/test-lib.sh
skip_if_root_

d1=no-$$
dir=/$d1/such-dir
# Ensure that $d1 doesn't already exist.
ls -d $d1 2> /dev/null && framework_failure

fail=0

touch $dir > out 2>&1 && fail=1
cat <<EOF > exp
touch: cannot touch \`$dir': No such file or directory
EOF

compare out exp || fail=1

Exit $fail
