#!/bin/sh
# Make sure touch works on fifos without hanging.

# Copyright (C) 2000, 2007 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

. $srcdir/../test-lib.sh

if ! mkfifo fifo; then
  # Make an exception of this case -- usually we interpret framework-creation
  # failure as a test failure.  However, in this case, when running on a SunOS
  # system using a disk NFS mounted from OpenBSD, the above fails like this:
  # mkfifo: cannot make fifo `fifo-10558': Not owner
  echo '********************************************'
  echo 'NOTICE: unable to create test prerequisites'
  echo '********************************************'
  exit 77
fi

fail=0

touch fifo || fail=1

exit $fail
