#!/bin/sh
# Ensure that touch -c no-such-file no longer fails (it did in 4.1.8).

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

pwd=`pwd`
tmp=`echo "$0"|sed 's,.*/,,'`.tmp
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

touch -c no-file > /dev/null 2>&1 || fail=1
touch -cm no-file > /dev/null 2>&1 || fail=1
touch -ca no-file > /dev/null 2>&1 || fail=1

(exit $fail); exit
