#!/bin/sh
# Test touch with obsolescent 8- or 10-digit time stamps.

_POSIX2_VERSION=199209; export _POSIX2_VERSION
POSIXLY_CORRECT=1; export POSIXLY_CORRECT

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

pwd=`pwd`
tmp=obsol.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

fail=0

yearstart=01010000

for ones in 11111111 1111111111; do
  for args in $ones "-- $ones" "$yearstart $ones" "-- $yearstart $ones"; do
    touch $args || fail=1
    test -f $ones || fail=1
    test -f $yearstart && fail=1
    rm -f $ones || fail=1
  done
done

(exit $fail); exit $fail
