#!/bin/sh
# ensure that touch can operate on read-only files

if test "$VERBOSE" = yes; then
  set -x
  touch --version
fi

PRIV_CHECK_ARG=require-non-root . $srcdir/../priv-check

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

: > read-only || framework_failure=1
chmod 444 read-only || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

touch read-only || fail=1

touch - 1< read-only 2> /dev/null && { test ! -f - || fail=1; }

(exit $fail); exit $fail
