#!/bin/sh
# make sure rmdir -p works on a directory specified with a trailing slash

if test "$VERBOSE" = yes; then
  set -x
  rmdir --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir dir || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# Prior to coreutils-4.5.2, this would fail with the following:
# rmdir: `dir': No such file or directory
rmdir -p dir/ || fail=1

(exit $fail); exit $fail
