#!/bin/sh
# Verify that `od -N N' reads no more than N bytes of input.

if test "$VERBOSE" = yes; then
  set -x
  od --version
fi

pwd=`pwd`
tmp=od-N.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
echo abcdefg > in || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit 1
fi

fail=0

(od -An -N3 -c; od -An -N3 -c) < in > out
cat <<EOF > exp || fail=1
   a   b   c
   d   e   f
EOF
cmp out exp || {
  fail=1
  diff out exp 2> /dev/null
  }

(exit $fail); exit $fail
