#!/bin/sh
# show that the following no longer makes ls infloop
# mkdir loop; cd loop; ln -s ../loop sub; ls -RL

if test "$VERBOSE" = yes; then
  set -x
  ls --version
fi

. $srcdir/../lang-default

pwd=`pwd`
tmp=infloop.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir loop || framework_failure=1
ln -s ../loop loop/sub || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit 1
fi

fail=0

ls -RL loop 2>err | head -n 7 > out
# With an inf-looping ls, out will contain these 7 lines:
cat <<EOF > bad
loop:
sub

loop/sub:
sub

loop/sub/sub:
EOF

cmp out bad 2>/dev/null && fail=1

(exit $fail); exit $fail
