#!/bin/sh
# show that the following no longer makes ls infloop
# mkdir loop; cd loop; ln -s ../loop sub; ls -RL

# Copyright (C) 2001-2002, 2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ls --version
fi

. $srcdir/test-lib.sh

mkdir loop || framework_failure
ln -s ../loop loop/sub || framework_failure

fail=0

ls -RL loop 2>err | head -n 7 > out
# With an inf-looping ls, out will contain these 7 lines:
cat <<EOF > bad
loop:
sub

loop/sub:
sub

loop/sub/sub:
EOF

# Make sure we don't get the "bad" output.
compare out bad > /dev/null 2>&1 && fail=1

Exit $fail
