#!/bin/sh
# make sure ls and `ls -R' do the right thing when invoked with no arguments.

if test "$VERBOSE" = yes; then
  set -x
  ls --version
fi

pwd=`pwd`
tmp=no-args.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
mkdir -p dir/subdir || framework_failure=1
touch dir/subdir/file2 || framework_failure=1
ln -s f symlink || framework_failure=1

cat > exp <<\EOF || framework_failure=1
dir
exp
out
symlink
EOF

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

fail=0

ls > out || fail=1

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

cat > exp <<\EOF
.:
dir
exp
out
symlink

./dir:
subdir

./dir/subdir:
file2
EOF

ls -R > out || fail=1

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit
