#!/bin/sh
# make sure ls and `ls -R' do the right thing when invoked with no arguments.

# Copyright (C) 2001, 2003, 2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ls --version
fi

. $srcdir/test-lib.sh

mkdir -p dir/subdir || framework_failure
touch dir/subdir/file2 || framework_failure
ln -s f symlink || framework_failure

cat > exp <<\EOF || framework_failure
dir
exp
out
symlink
EOF

fail=0

ls -1 > out || fail=1

compare out exp || fail=1

cat > exp <<\EOF
.:
dir
exp
out
symlink

./dir:
subdir

./dir/subdir:
file2
EOF

ls -R1 > out || fail=1

compare out exp || fail=1

Exit $fail
