#!/bin/sh
# Make sure name is used as secondary key when sorting on mtime or ctime.

. $srcdir/../envvar-check
. $srcdir/../lang-default

if test "$VERBOSE" = yes; then
  set -x
  ls --version
  touch --version
fi

pwd=`pwd`
tmp=t-ls.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

date=1998-01-15

touch -d "$date" c || framework_failure=1
touch -d "$date" a || framework_failure=1
touch -d "$date" b || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

ls -1t a b c > out || fail=1
cat <<EOF > exp
a
b
c
EOF
cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

rm -rf out exp
ls -1rt a b c > out || fail=1
cat <<EOF > exp
c
b
a
EOF
cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit
