#!/bin/sh

: ${LS=ls}
test=time-1

if test "$VERBOSE" = yes; then
  set -x
  $LS --version
fi

tmp=t-ls.$$

# We're going to LS from a subdir.  Prepend ../ if $LS is not an
# absolute file name.
case $LS in
  /*) ;;
  *) LS=../$LS
esac

test_failure=0
mkdir $tmp || test_failure=1
cd $tmp || test_failure=1

: > a || test_failure=1
sleep 1
: > b || test_failure=1

if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0
set `$LS -u a b`
test "$*" = 'b a' && : || fail=1

cd ..
rm -rf $tmp

exit $fail
