#!/bin/sh
# make sure chown --from=... works

if test "$VERBOSE" = yes; then
  set -x
  chgrp --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default
PRIV_CHECK_ARG=require-root . $srcdir/../priv-check

pwd=`pwd`
tmp=basic.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
touch f || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit 1
fi

fail=0
chown -R --preserve-root 0:1 f

# Make sure the owner and group are 0 and 1 respectively.
set _ `ls -n f`; shift; test "$3:$4" = 0:1 || fail=1

chown --from=0:1 2:010 f || fail=1

# And now they should be 2 and 10 respectively.
set _ `ls -n f`; shift; test "$3:$4" = 2:10 || fail=1

ln -s f slink
# Applying chown to a symlink with --no-dereference
# should change only the link.
chown --no-dereference 0:1 slink || fail=1
# owner/group on the symlink should be set
set _ `ls -n slink`; shift; test "$3:$4" = 0:1 || fail=1
# owner/group on the referent should remain unchanged
set _ `ls -n f`;     shift; test "$3:$4" = 2:10 || fail=1

chown --no-dereference --from=0:1 2:010 slink || fail=1
# owner/group on the symlink should be changed
set _ `ls -n slink`; shift; test "$3:$4" = 2:10 || fail=1

(exit $fail); exit $fail
