#! /bin/sh
# This script was generated automatically by build-script.
case $# in
  0) xx='../../src/tac';;
  *) xx="$1";;
esac
test "$VERBOSE" && echo=echo || echo=:
$echo testing program: $xx
errors=0
test "$srcdir" || srcdir=.
test "$VERBOSE" && $xx --version 2> /dev/null

# Make sure we get English translations.
LANGUAGE=C
export LANGUAGE
LC_ALL=C
export LC_ALL
LANG=C
export LANG

$xx  $srcdir/basic-a.I > basic-a.O 2> basic-a.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-a(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-a.O $srcdir/basic-a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-a(F)"; fi ;;
    1) $echo "Test basic-a(F) failed: files basic-a.O and $srcdir/basic-a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-a(F) may have failed." 1>&2;
       $echo The command "cmp basic-a.O $srcdir/basic-a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-a.E || rm -f basic-a.E
cat $srcdir/basic-a.I | $xx  > basic-a.O 2> basic-a.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-a(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-a.O $srcdir/basic-a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-a(|)"; fi ;;
    1) $echo "Test basic-a(|) failed: files basic-a.O and $srcdir/basic-a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-a(|) may have failed." 1>&2;
       $echo The command "cmp basic-a.O $srcdir/basic-a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-a.E || rm -f basic-a.E
$xx  < $srcdir/basic-a.I > basic-a.O 2> basic-a.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-a(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-a.O $srcdir/basic-a.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-a(<)"; fi ;;
    1) $echo "Test basic-a(<) failed: files basic-a.O and $srcdir/basic-a.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-a(<) may have failed." 1>&2;
       $echo The command "cmp basic-a.O $srcdir/basic-a.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-a.E || rm -f basic-a.E
$xx  $srcdir/basic-b.I > basic-b.O 2> basic-b.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-b(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-b.O $srcdir/basic-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-b(F)"; fi ;;
    1) $echo "Test basic-b(F) failed: files basic-b.O and $srcdir/basic-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-b(F) may have failed." 1>&2;
       $echo The command "cmp basic-b.O $srcdir/basic-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-b.E || rm -f basic-b.E
cat $srcdir/basic-b.I | $xx  > basic-b.O 2> basic-b.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-b(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-b.O $srcdir/basic-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-b(|)"; fi ;;
    1) $echo "Test basic-b(|) failed: files basic-b.O and $srcdir/basic-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-b(|) may have failed." 1>&2;
       $echo The command "cmp basic-b.O $srcdir/basic-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-b.E || rm -f basic-b.E
$xx  < $srcdir/basic-b.I > basic-b.O 2> basic-b.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-b(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-b.O $srcdir/basic-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-b(<)"; fi ;;
    1) $echo "Test basic-b(<) failed: files basic-b.O and $srcdir/basic-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-b(<) may have failed." 1>&2;
       $echo The command "cmp basic-b.O $srcdir/basic-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-b.E || rm -f basic-b.E
$xx  $srcdir/basic-c.I > basic-c.O 2> basic-c.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-c(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-c.O $srcdir/basic-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-c(F)"; fi ;;
    1) $echo "Test basic-c(F) failed: files basic-c.O and $srcdir/basic-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-c(F) may have failed." 1>&2;
       $echo The command "cmp basic-c.O $srcdir/basic-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-c.E || rm -f basic-c.E
cat $srcdir/basic-c.I | $xx  > basic-c.O 2> basic-c.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-c(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-c.O $srcdir/basic-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-c(|)"; fi ;;
    1) $echo "Test basic-c(|) failed: files basic-c.O and $srcdir/basic-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-c(|) may have failed." 1>&2;
       $echo The command "cmp basic-c.O $srcdir/basic-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-c.E || rm -f basic-c.E
$xx  < $srcdir/basic-c.I > basic-c.O 2> basic-c.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-c(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-c.O $srcdir/basic-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-c(<)"; fi ;;
    1) $echo "Test basic-c(<) failed: files basic-c.O and $srcdir/basic-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-c(<) may have failed." 1>&2;
       $echo The command "cmp basic-c.O $srcdir/basic-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-c.E || rm -f basic-c.E
$xx  $srcdir/basic-d.I > basic-d.O 2> basic-d.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-d(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-d.O $srcdir/basic-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-d(F)"; fi ;;
    1) $echo "Test basic-d(F) failed: files basic-d.O and $srcdir/basic-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-d(F) may have failed." 1>&2;
       $echo The command "cmp basic-d.O $srcdir/basic-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-d.E || rm -f basic-d.E
cat $srcdir/basic-d.I | $xx  > basic-d.O 2> basic-d.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-d(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-d.O $srcdir/basic-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-d(|)"; fi ;;
    1) $echo "Test basic-d(|) failed: files basic-d.O and $srcdir/basic-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-d(|) may have failed." 1>&2;
       $echo The command "cmp basic-d.O $srcdir/basic-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-d.E || rm -f basic-d.E
$xx  < $srcdir/basic-d.I > basic-d.O 2> basic-d.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-d(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-d.O $srcdir/basic-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-d(<)"; fi ;;
    1) $echo "Test basic-d(<) failed: files basic-d.O and $srcdir/basic-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-d(<) may have failed." 1>&2;
       $echo The command "cmp basic-d.O $srcdir/basic-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-d.E || rm -f basic-d.E
$xx  $srcdir/basic-e.I > basic-e.O 2> basic-e.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-e(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-e.O $srcdir/basic-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-e(F)"; fi ;;
    1) $echo "Test basic-e(F) failed: files basic-e.O and $srcdir/basic-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-e(F) may have failed." 1>&2;
       $echo The command "cmp basic-e.O $srcdir/basic-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-e.E || rm -f basic-e.E
cat $srcdir/basic-e.I | $xx  > basic-e.O 2> basic-e.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-e(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-e.O $srcdir/basic-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-e(|)"; fi ;;
    1) $echo "Test basic-e(|) failed: files basic-e.O and $srcdir/basic-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-e(|) may have failed." 1>&2;
       $echo The command "cmp basic-e.O $srcdir/basic-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-e.E || rm -f basic-e.E
$xx  < $srcdir/basic-e.I > basic-e.O 2> basic-e.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-e(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-e.O $srcdir/basic-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-e(<)"; fi ;;
    1) $echo "Test basic-e(<) failed: files basic-e.O and $srcdir/basic-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-e(<) may have failed." 1>&2;
       $echo The command "cmp basic-e.O $srcdir/basic-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-e.E || rm -f basic-e.E
$xx  $srcdir/basic-f.I > basic-f.O 2> basic-f.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-f(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-f.O $srcdir/basic-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-f(F)"; fi ;;
    1) $echo "Test basic-f(F) failed: files basic-f.O and $srcdir/basic-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-f(F) may have failed." 1>&2;
       $echo The command "cmp basic-f.O $srcdir/basic-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-f.E || rm -f basic-f.E
cat $srcdir/basic-f.I | $xx  > basic-f.O 2> basic-f.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-f(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-f.O $srcdir/basic-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-f(|)"; fi ;;
    1) $echo "Test basic-f(|) failed: files basic-f.O and $srcdir/basic-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-f(|) may have failed." 1>&2;
       $echo The command "cmp basic-f.O $srcdir/basic-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-f.E || rm -f basic-f.E
$xx  < $srcdir/basic-f.I > basic-f.O 2> basic-f.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-f(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-f.O $srcdir/basic-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-f(<)"; fi ;;
    1) $echo "Test basic-f(<) failed: files basic-f.O and $srcdir/basic-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-f(<) may have failed." 1>&2;
       $echo The command "cmp basic-f.O $srcdir/basic-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-f.E || rm -f basic-f.E
$xx  $srcdir/basic-g.I > basic-g.O 2> basic-g.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-g(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-g.O $srcdir/basic-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-g(F)"; fi ;;
    1) $echo "Test basic-g(F) failed: files basic-g.O and $srcdir/basic-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-g(F) may have failed." 1>&2;
       $echo The command "cmp basic-g.O $srcdir/basic-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-g.E || rm -f basic-g.E
cat $srcdir/basic-g.I | $xx  > basic-g.O 2> basic-g.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-g(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-g.O $srcdir/basic-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-g(|)"; fi ;;
    1) $echo "Test basic-g(|) failed: files basic-g.O and $srcdir/basic-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-g(|) may have failed." 1>&2;
       $echo The command "cmp basic-g.O $srcdir/basic-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-g.E || rm -f basic-g.E
$xx  < $srcdir/basic-g.I > basic-g.O 2> basic-g.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-g(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-g.O $srcdir/basic-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-g(<)"; fi ;;
    1) $echo "Test basic-g(<) failed: files basic-g.O and $srcdir/basic-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-g(<) may have failed." 1>&2;
       $echo The command "cmp basic-g.O $srcdir/basic-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-g.E || rm -f basic-g.E
$xx  $srcdir/basic-h.I > basic-h.O 2> basic-h.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-h(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-h.O $srcdir/basic-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-h(F)"; fi ;;
    1) $echo "Test basic-h(F) failed: files basic-h.O and $srcdir/basic-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-h(F) may have failed." 1>&2;
       $echo The command "cmp basic-h.O $srcdir/basic-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-h.E || rm -f basic-h.E
cat $srcdir/basic-h.I | $xx  > basic-h.O 2> basic-h.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-h(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-h.O $srcdir/basic-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-h(|)"; fi ;;
    1) $echo "Test basic-h(|) failed: files basic-h.O and $srcdir/basic-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-h(|) may have failed." 1>&2;
       $echo The command "cmp basic-h.O $srcdir/basic-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-h.E || rm -f basic-h.E
$xx  < $srcdir/basic-h.I > basic-h.O 2> basic-h.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-h(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-h.O $srcdir/basic-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-h(<)"; fi ;;
    1) $echo "Test basic-h(<) failed: files basic-h.O and $srcdir/basic-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-h(<) may have failed." 1>&2;
       $echo The command "cmp basic-h.O $srcdir/basic-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-h.E || rm -f basic-h.E
$xx  $srcdir/basic-i.I > basic-i.O 2> basic-i.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-i(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-i.O $srcdir/basic-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-i(F)"; fi ;;
    1) $echo "Test basic-i(F) failed: files basic-i.O and $srcdir/basic-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-i(F) may have failed." 1>&2;
       $echo The command "cmp basic-i.O $srcdir/basic-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-i.E || rm -f basic-i.E
cat $srcdir/basic-i.I | $xx  > basic-i.O 2> basic-i.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-i(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-i.O $srcdir/basic-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-i(|)"; fi ;;
    1) $echo "Test basic-i(|) failed: files basic-i.O and $srcdir/basic-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-i(|) may have failed." 1>&2;
       $echo The command "cmp basic-i.O $srcdir/basic-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-i.E || rm -f basic-i.E
$xx  < $srcdir/basic-i.I > basic-i.O 2> basic-i.E
code=$?
if test $code != 0 ; then
  $echo "Test basic-i(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp basic-i.O $srcdir/basic-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed basic-i(<)"; fi ;;
    1) $echo "Test basic-i(<) failed: files basic-i.O and $srcdir/basic-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test basic-i(<) may have failed." 1>&2;
       $echo The command "cmp basic-i.O $srcdir/basic-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s basic-i.E || rm -f basic-i.E
$xx  $srcdir/empty.I > empty.O 2> empty.E
code=$?
if test $code != 0 ; then
  $echo "Test empty(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp empty.O $srcdir/empty.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed empty(F)"; fi ;;
    1) $echo "Test empty(F) failed: files empty.O and $srcdir/empty.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test empty(F) may have failed." 1>&2;
       $echo The command "cmp empty.O $srcdir/empty.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s empty.E || rm -f empty.E
cat $srcdir/empty.I | $xx  > empty.O 2> empty.E
code=$?
if test $code != 0 ; then
  $echo "Test empty(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp empty.O $srcdir/empty.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed empty(|)"; fi ;;
    1) $echo "Test empty(|) failed: files empty.O and $srcdir/empty.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test empty(|) may have failed." 1>&2;
       $echo The command "cmp empty.O $srcdir/empty.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s empty.E || rm -f empty.E
$xx  < $srcdir/empty.I > empty.O 2> empty.E
code=$?
if test $code != 0 ; then
  $echo "Test empty(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp empty.O $srcdir/empty.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed empty(<)"; fi ;;
    1) $echo "Test empty(<) failed: files empty.O and $srcdir/empty.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test empty(<) may have failed." 1>&2;
       $echo The command "cmp empty.O $srcdir/empty.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s empty.E || rm -f empty.E
$xx  $srcdir/no-nl-b.I > no-nl-b.O 2> no-nl-b.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-b(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-b.O $srcdir/no-nl-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-b(F)"; fi ;;
    1) $echo "Test no-nl-b(F) failed: files no-nl-b.O and $srcdir/no-nl-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-b(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-b.O $srcdir/no-nl-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-b.E || rm -f no-nl-b.E
cat $srcdir/no-nl-b.I | $xx  > no-nl-b.O 2> no-nl-b.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-b(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-b.O $srcdir/no-nl-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-b(|)"; fi ;;
    1) $echo "Test no-nl-b(|) failed: files no-nl-b.O and $srcdir/no-nl-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-b(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-b.O $srcdir/no-nl-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-b.E || rm -f no-nl-b.E
$xx  < $srcdir/no-nl-b.I > no-nl-b.O 2> no-nl-b.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-b(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-b.O $srcdir/no-nl-b.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-b(<)"; fi ;;
    1) $echo "Test no-nl-b(<) failed: files no-nl-b.O and $srcdir/no-nl-b.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-b(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-b.O $srcdir/no-nl-b.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-b.E || rm -f no-nl-b.E
$xx  $srcdir/no-nl-c.I > no-nl-c.O 2> no-nl-c.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-c(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-c.O $srcdir/no-nl-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-c(F)"; fi ;;
    1) $echo "Test no-nl-c(F) failed: files no-nl-c.O and $srcdir/no-nl-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-c(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-c.O $srcdir/no-nl-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-c.E || rm -f no-nl-c.E
cat $srcdir/no-nl-c.I | $xx  > no-nl-c.O 2> no-nl-c.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-c(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-c.O $srcdir/no-nl-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-c(|)"; fi ;;
    1) $echo "Test no-nl-c(|) failed: files no-nl-c.O and $srcdir/no-nl-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-c(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-c.O $srcdir/no-nl-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-c.E || rm -f no-nl-c.E
$xx  < $srcdir/no-nl-c.I > no-nl-c.O 2> no-nl-c.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-c(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-c.O $srcdir/no-nl-c.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-c(<)"; fi ;;
    1) $echo "Test no-nl-c(<) failed: files no-nl-c.O and $srcdir/no-nl-c.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-c(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-c.O $srcdir/no-nl-c.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-c.E || rm -f no-nl-c.E
$xx  $srcdir/no-nl-d.I > no-nl-d.O 2> no-nl-d.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-d(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-d.O $srcdir/no-nl-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-d(F)"; fi ;;
    1) $echo "Test no-nl-d(F) failed: files no-nl-d.O and $srcdir/no-nl-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-d(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-d.O $srcdir/no-nl-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-d.E || rm -f no-nl-d.E
cat $srcdir/no-nl-d.I | $xx  > no-nl-d.O 2> no-nl-d.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-d(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-d.O $srcdir/no-nl-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-d(|)"; fi ;;
    1) $echo "Test no-nl-d(|) failed: files no-nl-d.O and $srcdir/no-nl-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-d(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-d.O $srcdir/no-nl-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-d.E || rm -f no-nl-d.E
$xx  < $srcdir/no-nl-d.I > no-nl-d.O 2> no-nl-d.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-d(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-d.O $srcdir/no-nl-d.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-d(<)"; fi ;;
    1) $echo "Test no-nl-d(<) failed: files no-nl-d.O and $srcdir/no-nl-d.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-d(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-d.O $srcdir/no-nl-d.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-d.E || rm -f no-nl-d.E
$xx  $srcdir/no-nl-e.I > no-nl-e.O 2> no-nl-e.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-e(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-e.O $srcdir/no-nl-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-e(F)"; fi ;;
    1) $echo "Test no-nl-e(F) failed: files no-nl-e.O and $srcdir/no-nl-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-e(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-e.O $srcdir/no-nl-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-e.E || rm -f no-nl-e.E
cat $srcdir/no-nl-e.I | $xx  > no-nl-e.O 2> no-nl-e.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-e(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-e.O $srcdir/no-nl-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-e(|)"; fi ;;
    1) $echo "Test no-nl-e(|) failed: files no-nl-e.O and $srcdir/no-nl-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-e(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-e.O $srcdir/no-nl-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-e.E || rm -f no-nl-e.E
$xx  < $srcdir/no-nl-e.I > no-nl-e.O 2> no-nl-e.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-e(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-e.O $srcdir/no-nl-e.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-e(<)"; fi ;;
    1) $echo "Test no-nl-e(<) failed: files no-nl-e.O and $srcdir/no-nl-e.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-e(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-e.O $srcdir/no-nl-e.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-e.E || rm -f no-nl-e.E
$xx  $srcdir/no-nl-f.I > no-nl-f.O 2> no-nl-f.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-f(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-f.O $srcdir/no-nl-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-f(F)"; fi ;;
    1) $echo "Test no-nl-f(F) failed: files no-nl-f.O and $srcdir/no-nl-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-f(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-f.O $srcdir/no-nl-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-f.E || rm -f no-nl-f.E
cat $srcdir/no-nl-f.I | $xx  > no-nl-f.O 2> no-nl-f.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-f(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-f.O $srcdir/no-nl-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-f(|)"; fi ;;
    1) $echo "Test no-nl-f(|) failed: files no-nl-f.O and $srcdir/no-nl-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-f(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-f.O $srcdir/no-nl-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-f.E || rm -f no-nl-f.E
$xx  < $srcdir/no-nl-f.I > no-nl-f.O 2> no-nl-f.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-f(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-f.O $srcdir/no-nl-f.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-f(<)"; fi ;;
    1) $echo "Test no-nl-f(<) failed: files no-nl-f.O and $srcdir/no-nl-f.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-f(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-f.O $srcdir/no-nl-f.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-f.E || rm -f no-nl-f.E
$xx  $srcdir/no-nl-g.I > no-nl-g.O 2> no-nl-g.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-g(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-g.O $srcdir/no-nl-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-g(F)"; fi ;;
    1) $echo "Test no-nl-g(F) failed: files no-nl-g.O and $srcdir/no-nl-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-g(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-g.O $srcdir/no-nl-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-g.E || rm -f no-nl-g.E
cat $srcdir/no-nl-g.I | $xx  > no-nl-g.O 2> no-nl-g.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-g(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-g.O $srcdir/no-nl-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-g(|)"; fi ;;
    1) $echo "Test no-nl-g(|) failed: files no-nl-g.O and $srcdir/no-nl-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-g(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-g.O $srcdir/no-nl-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-g.E || rm -f no-nl-g.E
$xx  < $srcdir/no-nl-g.I > no-nl-g.O 2> no-nl-g.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-g(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-g.O $srcdir/no-nl-g.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-g(<)"; fi ;;
    1) $echo "Test no-nl-g(<) failed: files no-nl-g.O and $srcdir/no-nl-g.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-g(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-g.O $srcdir/no-nl-g.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-g.E || rm -f no-nl-g.E
$xx  $srcdir/no-nl-h.I > no-nl-h.O 2> no-nl-h.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-h(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-h.O $srcdir/no-nl-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-h(F)"; fi ;;
    1) $echo "Test no-nl-h(F) failed: files no-nl-h.O and $srcdir/no-nl-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-h(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-h.O $srcdir/no-nl-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-h.E || rm -f no-nl-h.E
cat $srcdir/no-nl-h.I | $xx  > no-nl-h.O 2> no-nl-h.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-h(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-h.O $srcdir/no-nl-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-h(|)"; fi ;;
    1) $echo "Test no-nl-h(|) failed: files no-nl-h.O and $srcdir/no-nl-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-h(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-h.O $srcdir/no-nl-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-h.E || rm -f no-nl-h.E
$xx  < $srcdir/no-nl-h.I > no-nl-h.O 2> no-nl-h.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-h(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-h.O $srcdir/no-nl-h.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-h(<)"; fi ;;
    1) $echo "Test no-nl-h(<) failed: files no-nl-h.O and $srcdir/no-nl-h.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-h(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-h.O $srcdir/no-nl-h.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-h.E || rm -f no-nl-h.E
$xx  $srcdir/no-nl-i.I > no-nl-i.O 2> no-nl-i.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-i(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-i.O $srcdir/no-nl-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-i(F)"; fi ;;
    1) $echo "Test no-nl-i(F) failed: files no-nl-i.O and $srcdir/no-nl-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-i(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-i.O $srcdir/no-nl-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-i.E || rm -f no-nl-i.E
cat $srcdir/no-nl-i.I | $xx  > no-nl-i.O 2> no-nl-i.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-i(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-i.O $srcdir/no-nl-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-i(|)"; fi ;;
    1) $echo "Test no-nl-i(|) failed: files no-nl-i.O and $srcdir/no-nl-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-i(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-i.O $srcdir/no-nl-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-i.E || rm -f no-nl-i.E
$xx  < $srcdir/no-nl-i.I > no-nl-i.O 2> no-nl-i.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-i(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-i.O $srcdir/no-nl-i.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-i(<)"; fi ;;
    1) $echo "Test no-nl-i(<) failed: files no-nl-i.O and $srcdir/no-nl-i.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-i(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-i.O $srcdir/no-nl-i.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-i.E || rm -f no-nl-i.E
$xx  $srcdir/no-nl-j.I > no-nl-j.O 2> no-nl-j.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-j(F) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-j.O $srcdir/no-nl-j.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-j(F)"; fi ;;
    1) $echo "Test no-nl-j(F) failed: files no-nl-j.O and $srcdir/no-nl-j.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-j(F) may have failed." 1>&2;
       $echo The command "cmp no-nl-j.O $srcdir/no-nl-j.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-j.E || rm -f no-nl-j.E
cat $srcdir/no-nl-j.I | $xx  > no-nl-j.O 2> no-nl-j.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-j(|) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-j.O $srcdir/no-nl-j.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-j(|)"; fi ;;
    1) $echo "Test no-nl-j(|) failed: files no-nl-j.O and $srcdir/no-nl-j.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-j(|) may have failed." 1>&2;
       $echo The command "cmp no-nl-j.O $srcdir/no-nl-j.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-j.E || rm -f no-nl-j.E
$xx  < $srcdir/no-nl-j.I > no-nl-j.O 2> no-nl-j.E
code=$?
if test $code != 0 ; then
  $echo "Test no-nl-j(<) failed: ../../src/tac return code $code differs from expected value 0" 1>&2
  errors=`expr $errors + 1`
else
  cmp no-nl-j.O $srcdir/no-nl-j.X > /dev/null 2>&1
  case $? in
    0) if test "$VERBOSE" ; then $echo "passed no-nl-j(<)"; fi ;;
    1) $echo "Test no-nl-j(<) failed: files no-nl-j.O and $srcdir/no-nl-j.X differ" 1>&2;
       errors=`expr $errors + 1` ;;
    2) $echo "Test no-nl-j(<) may have failed." 1>&2;
       $echo The command "cmp no-nl-j.O $srcdir/no-nl-j.X" failed. 1>&2 ;
       errors=`expr $errors + 1` ;;
  esac
fi
test -s no-nl-j.E || rm -f no-nl-j.E
if test $errors = 0 ; then
  $echo Passed all 57 tests. 1>&2
else
  $echo Failed $errors tests. 1>&2
fi
test $errors = 0 || errors=1
exit $errors
