#!/bin/sh
# Verify that chmod's --changes (-c) option works.

# Copyright (C) 2000, 2004, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  chmod --version
fi

. $srcdir/test-lib.sh

umask 0
file=f
touch $file || framework_failure
chmod 444 $file || framework_failure

skip_if_setgid_

fail=0

chmod u=rwx $file || fail=1
chmod -c g=rwx $file > out || fail=1
chmod -c g=rwx $file > empty || fail=1

test -s empty && fail=1
case "`cat out`" in
  "mode of \`f' changed to 0774 "?rwxrwxr--?) ;;
  *) fail=1 ;;
esac

Exit $fail
