#!/bin/sh
# Verify that chmod's --changes (-c) option works.

if test "$VERBOSE" = yes; then
  set -x
  chmod --version
fi

. $srcdir/../lang-default

pwd=`pwd`
tmp=eq-x-$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0

# Record absolute path of srcdir.
cd $srcdir || framework_failure=1
abs_srcdir=`pwd`

cd $pwd || framework_failure=1
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

umask 0
file=f
touch $file || framework_failure=1
chmod 444 $file || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

. $abs_srcdir/../setgid-check

fail=0

chmod u=rwx $file || fail=1
chmod -c g=rwx $file > out || fail=1
chmod -c g=rwx $file > empty || fail=1

test -s empty && fail=1
case "`cat out`" in
  "mode of \`f' changed to 0774 "?rwxrwxr--?) ;;
  *) fail=1 ;;
esac

(exit $fail); exit
