#!/bin/sh

if test "$VERBOSE" = yes; then
  set -x
  chmod --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

file=f
touch $file || framework_failure=1
chmod 444 $file || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

umask 005
chmod =x $file
case "`ls -l $file`" in
  ---x--x---*) fail=0 ;;
  *) fail=1; ls -l $file ;;
esac

(exit $fail); exit
