#!/bin/sh
# Make sure GNU chmod works the same way as those of Solaris, HPUX, AIX
# wrt directories with the setgid bit set.

if test "$VERBOSE" = yes; then
  set -x
  chmod --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default

pwd=`pwd`
tmp=setgid.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0

# Record absolute path of srcdir and cd back to current dir.
cd $srcdir || framework_failure=1
abs_srcdir=`pwd`
cd $pwd || framework_failure=1

mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

. $abs_srcdir/../setgid-check

umask 0
mkdir d || framework_failure=1

chmod g+s d 2> /dev/null ||
  {
    # This is required because on some systems (at least NetBSD 1.4.2A),
    # it may happen that when you create a directory, its group isn't one
    # to which you belong.  When that happens, the above chmod fails.  So
    # here, upon failure, we try to set the group, then rerun the chmod command.
    group=${COREUTILS_GROUP-`(id -g || /usr/xpg4/bin/id -g) 2>/dev/null`}
    if test "$group"; then
      chgrp "$group" d || framework_failure=1
      chmod g+s d || framework_failure=1
    else
      framework_failure=1
    fi
  }

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit 1
fi

fail=0

chmod 755 d

# To be compatible with chmod from other vendors,
# GNU chmod must not reset a directory's setgid bit.
# The latest POSIX draft (d5) allows either behavior.  It says:
#
#   For regular files, for each bit set in the octal number
#   corresponding to the set-user-ID-on-execution or the
#   set-group-ID-on-execution, bits shown in the following table shall
#   be set; if these bits are not set in the octal number, they are
#   cleared. For other file types, it is implementation-defined whether
#   or not requests to set or clear the set-user-ID-on-execution or
#   set-group-ID-on-execution bits are honored.

# FIXME: consider changing GNU chmod to work like other versions of chmod.
# For now, this test simply confirms the existing behavior.
p=`ls -ld d|sed 's/ .*//'`; case $p in drwxr-xr-x);; *) fail=1;; esac

(exit $fail); exit $fail
