#!/bin/sh
# Make sure GNU chmod works the same way as those of Solaris, HPUX, AIX
# wrt directories with the setgid bit set.

if test "$VERBOSE" = yes; then
  set -x
  chmod --version
fi

. $srcdir/../envvar-check
. $srcdir/../lang-default

pwd=`pwd`
tmp=setgid.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0

mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

test=../../../src/test

umask 0
mkdir d || framework_failure=1

chmod g+s d 2> /dev/null && $test -g d ||
  {
    # This is required because on some systems (at least NetBSD 1.4.2A),
    # it may happen that when you create a directory, its group isn't one
    # to which you belong.  When that happens, the above chmod fails.  So
    # here, upon failure, we try to set the group, then rerun the chmod command.

    id_g=`id -g` &&
    test -n "$id_g" &&
    chgrp "$id_g" d &&
    chmod g+s d || framework_failure=1
  }

if test $framework_failure = 1; then
  echo 'failure in testing framework' 1>&2
  (exit 1); exit 1
fi

# "chmod g+s d" does nothing on some NFS file systems.
$test -g d || {
  echo 1>&2 "$0: cannot create setgid directories," \
    "so can't run this test"
  exit 77
}

fail=0

chmod 755 d

case `ls -ld d` in drwxr-sr-x*);; *) fail=1;; esac

(exit $fail); exit $fail
