#!/bin/sh
# This test would fail on solaris5.7 with tail from pre-1.22k textutils.
# The problem was that using the solaris5.7 setvbuf function to turn off
# buffering doesn't flush stdout.

# Copyright (C) 1999, 2000, 2003, 2006-2007 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# FIXME: actually, I couldn't find a way to write the test (without resorting
# to use of expect) so that it would provoke the failure on solaris5.7.
# To exercise the bug, cat's stdout seems to have to be directed
# to a terminal.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

. $srcdir/../test-lib.sh

echo fubar > in
tail -f in | cat > out &
pid=$!
sleep 1
kill $pid

fail=0
test "`cat out`" = fubar || fail=1

exit $fail
