#!/bin/sh
# inotify-based tail -f didn't flush its initial output before blocking

# Copyright (C) 2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

. $srcdir/test-lib.sh

fail=0
echo line > in || fail=1
# Output should be buffered since we're writing to file
# so we're depending on the flush to write out
tail -f in > out &
tail_pid=$!

# Wait for 1 second for the file to be flushed.
for i in $(seq 10); do
  test -s out && break
  echo sleep .1s
  sleep .1
done

test -s out || fail=1

kill $tail_pid

Exit $fail
