#!/bin/sh
# This test would fail with tail from pre-1.22i textutils.

# Copyright (C) 1999, 2002, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

. $srcdir/test-lib.sh

yes > t &
yes_pid=$!
while :; do
  test -s t && break
done
tail -n 1 t &
tail_pid=$!
kill $yes_pid

# This test is racy, and can fail under unusual circumstances.
# On a busy system, "yes" will fail to write
# (and hence fail to be killed by SIGPIPE) in that 1-second interval.
# Then the following kill will succeed and cause this test to fail.
sleep 1

fail=0
kill $tail_pid && fail=1 || :

Exit $fail
