#!/bin/sh
# This test would fail with tail from pre-1.22i textutils.

# Copyright (C) 1999, 2002, 2006 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

tmp=tail-inf1.$$
pwd=`pwd`
trap 'cd "$pwd" && rm -rf $tmp' 0 1 2 3 15

test_failure=0
mkdir $tmp || test_failure=1
cd $tmp || test_failure=1

if test $test_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

yes > t &
yes_pid=$!
while :; do
  test -s t && break
done
tail -n 1 t &
tail_pid=$!
kill $yes_pid
sleep 1
kill $tail_pid
