#!/bin/sh
# Verify that tail works even when it's reading from a file
# that is not at its beginning.  Based on a report from John Roll.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

pwd=`pwd`
tmp=tail-mid.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

(echo 1; echo 2) > k || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit
fi

fail=0

sh -c 'read x; tail' < k > out || fail=1
cat <<EOF > exp
2
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit
