#!/bin/sh
# Make sure that `tail -f' returns immediately if a file doesn't exist
# while `tail -F' waits for it to appear.

# Copyright (C) 2003, 2006-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  tail --version
fi

. $srcdir/test-lib.sh

touch here || framework_failure
touch k || framework_failure
{ touch unreadable && chmod a-r unreadable; } || framework_failure

fail=0

for inotify in ---disable-inotify ''; do
  timeout 1 tail -s0.1 -f $inotify not_here
  test $? = 124 && fail=1

  if test ! -r unreadable; then # can't test this when root
    timeout 1 tail -s0.1 -f $inotify unreadable
    test $? = 124 && fail=1
  fi

  timeout 1 tail -s0.1 -f $inotify here 2>tail.err
  test $? = 124 || fail=1

  # `tail -F' must wait in any case.

  timeout 1 tail -s0.1 -F $inotify here 2>>tail.err
  test $? = 124 || fail=1

  if test ! -r unreadable; then # can't test this when root
    timeout 1 tail -s0.1 -F $inotify unreadable
    test $? = 124 || fail=1
  fi

  timeout 1 tail -s0.1 -F $inotify not_here
  test $? = 124 || fail=1


  test -s tail.err && fail=1
  :>tail.err


  tail -s.1 --max-unchanged-stats=2 -F $inotify k > tail.out &
  pid=$!
  sleep .5
  mv k l
  sleep .5
  touch k
  mv k l
  sleep .5
  echo NO >> l
  sleep .5
  kill $pid
  test -s tail.out && fail=1
done

Exit $fail
