#!/bin/sh

: ${PERL=perl}
: ${srcdir=.}

case "$PERL" in
  *'missing perl')
  echo 1>&2 "$0: configure didn't find a usable version of Perl, so can't run this test"
  exit 77
  ;;
esac

exec $PERL -w -I$srcdir/.. -MFetish -- - <<\EOF
require 5.003;
use strict;

(my $program_name = $0) =~ s|.*/||;

# Turn off localisation of executable's ouput.
@ENV{qw(LANGUAGE LANG LC_ALL)} = ('C') x 3;

my @Tests =
    (
     ['1', {IN=> {f=> ''}},	{OUT=>"00000     0\n"}],
     ['2', {IN=> {f=> 'a'}},	{OUT=>"00097     1\n"}],
     ['3', {IN=> {f=> 'abc'}},	{OUT=>"16556     1\n"}],
     ['4', {IN=> {f=> 'message digest'}}, {OUT=>"26423     1\n"}],
     ['5', {IN=> {f=> 'abcdefghijklmnopqrstuvwxyz'}}, {OUT=>"53553     1\n"}],
     ['6', {IN=> {f=> join ('', 'A'..'Z', 'a'..'z', '0'..'9')}},
				{OUT=>"25587     1\n"}],
     ['7', {IN=> {f=> '1234567890' x 8}}, {OUT=>"21845     1\n"}],
    );

my $save_temps = $ENV{DEBUG};
my $verbose = $ENV{VERBOSE};

my $prog = $ENV{PROG} || die "$0: \$PROG not specified in environment\n";
my $fail = run_tests ($program_name, $prog, \@Tests, $save_temps, $verbose);
exit $fail;
EOF
