#!/bin/sh
# make sure that --exact no longer gobbles a command line argument

if test "$VERBOSE" = yes; then
  set -x
  shred --version
fi

pwd=`pwd`
tmp=exact.$$
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1
echo a > a || framework_failure=1
echo bb > b || framework_failure=1
echo ccc > c || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit
fi

fail=0

shred --remove --exact a b || fail=1
test -f a && fail=1
test -f b && fail=1

shred --remove --exact c || fail=1
test -f c && fail=1

(exit $fail); exit
