#!/usr/bin/perl -w
# dcgen -- convert dircolors.hin to dircolors.h.

# Copyright (C) 1996, 1998, 2004, 2005 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# written by Jim Meyering

require 5.002;
use strict;
(my $ME = $0) =~ s|.*/||;

# A global destructor to close standard output with error checking.
sub END
{
  defined fileno STDOUT
    or return;
  close STDOUT
    and return;
  warn "$ME: closing standard output: $!\n";
  $? ||= 1;
}

my @line;
while (<>)
  {
    chomp;
    s/[[:blank:]]+/ /g;
    $_
      and push @line, $_;
  }

my $last_line = pop @line;
my $indent = '  ';

print "static char const G_line[] =\n";
foreach (@line)
  {
    print "$indent\"$_\\0\"\n";
  }
print "$indent\"$last_line\";\n";
