#!/usr/bin/perl -w
# -*- perl -*-

eval 'exec /p/bin/perl -S $0 ${1+"$@"}'
    if 0;

# dcgen -- generate C declarations of arrays of lines and line lengths
# Copyright (C) 1996, 1998, 2004, 2005 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

# written by Jim Meyering

# If you uncomment the following lines, you should also do
# s/chop/chomp and s/local/my/.
#require 5.002;
#use strict;

# Convert an arbitrary file to dcl of two arrays.
# One of lines, the other of lengths.

local $prefix = 'G_';

local @line;
while (<>)
  {
    chop;
    s/[[:blank:]]*#.*//;
    s/[[:blank:]]+/ /g;
    if ($_)
      {
	push (@line, $_);
      }
  }

local $indent = '  ';

print "static char const ${prefix}line[] =\n";
while (1)
  {
    $_ = shift (@line);
    if (!@line)
      {
	print "$indent\"$_\";\n";
	last;
      }
    print "$indent\"$_\\0\"\n";
  }

exit (0);
