#! /bin/sh

dir=dir
file=file

framework_failure=0

rm -rf $dir $file || framework_failure=1
mkdir -p $dir || framework_failure=1
echo foo > $file || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  exit 1
fi

fail=0
ginstall $file $dir || fail=1
# Make sure the source file still exists.
test -f $file || fail=1
# Make sure the dest file has been created.
test -f $dir/$file || fail=1

# This test would fail with 3.16s when using versions of strip that
# don't work on read-only files (the one from binutils works fine).
ginstall -s -c -m 555 ../../src/dd $dir || fail=1
# Make sure the dest file has been created.
test -f $dir/dd || fail=1

# ...and that the permissions are as requested.
set X `ls -l $dir/dd`
shift
test "$1" = -r-xr-xr-x || fail=1

rm -rf $dir $file

exit $fail
