#! /bin/sh
# Test -D option.

# Copyright (C) 2000, 2001, 2006 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Note that the tests below use `ginstall', not install, because
# that's the name of the binary in ../../src.

if test "$VERBOSE" = yes; then
  set -x
  ginstall --version
fi

. $srcdir/../envvar-check

pwd=`pwd`
dir=install-D$$

trap 'cd "$pwd" && rm -rf $dir' 0 1 2 3 15

mkdir $dir

fail=0
cd $dir
file=file
echo foo > $file

# Before 4.0q, this would mistakenly create $file, not `dest'
# in no-dir1/no-dir2/.
ginstall -D $file no-dir1/no-dir2/dest || fail=1
test -d no-dir1/no-dir2 || fail=1
test -r no-dir1/no-dir2/dest || fail=1

exit $fail
