#!/bin/sh
# Ensure that ginstall -d works with arguments specified with a trailing "/.".

if test "$VERBOSE" = yes; then
  set -x
  install --version
fi

pwd=`pwd`
tmp=`echo "$0"|sed 's,.*/,,'`.tmp
trap 'status=$?; cd $pwd; rm -rf $tmp && exit $status' 0
trap '(exit $?); exit' 1 2 13 15

framework_failure=0
mkdir $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo 'failure in testing framework'
  (exit 1); exit 1
fi

fail=0

ginstall -d d1/. || fail=1
test -d d1 || fail=1

ginstall -d d2/.. || fail=1
test -d d2 || fail=1

(exit $fail); exit $fail
