#!/bin/sh
# Ensure "install -C" compares SELinux context.

# Copyright (C) 2008-2009 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ginstall --version
fi

. $srcdir/test-lib.sh
require_selinux_

fail=0

echo test > a || framework_failure
chcon -u system_u a || skip_test_ "chcon doesn't work"

echo "\`a' -> \`b'" > out_installed_first
echo "removed \`b'
\`a' -> \`b'" > out_installed_second
> out_empty

# destination file does not exist
ginstall -Cv --preserve-context a b > out || fail=1
compare out out_installed_first || fail=1

# destination file exists
ginstall -Cv --preserve-context a b > out || fail=1
compare out out_empty || fail=1

# destination file exists but -C is not given
ginstall -v --preserve-context a b > out || fail=1
compare out out_installed_second || fail=1

# destination file exists but SELinux context differs
chcon -u unconfined_u a || skip_test_ "chcon doesn't work"
ginstall -Cv --preserve-context a b > out || fail=1
compare out out_installed_second || fail=1
ginstall -Cv --preserve-context a b > out || fail=1
compare out out_empty || fail=1

Exit $fail
