#!/bin/sh
# Ensure that `install -s' doesn't infloop when its parent
# process traps CHLD signal.

if test "$VERBOSE" = yes; then
  set -x
  ginstall --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

# Use a subshell and an exec to work around a bug in FreeBSD 5.0 /bin/sh.
(
  # ash doesn't support "trap '' CHLD"; it knows only signal numbers.
  sig=`$pwd/../../src/kill -l CHLD 2>/dev/null` && trap '' $sig

  # Before 2004-04-21, install would infloop, in the `while (wait...' loop:
  exec ginstall -s $pwd/../../src/ginstall$EXEEXT .
)

(exit $fail); exit $fail
